In [8]:
import pandas as pd

# File path
file_path = "Data/20250108_opendata_moni_23.csv"

# Load a small sample first because the full dataset is very large
df_sample = pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    nrows=10
)

# Preview the data
df_sample.head()

,Jahr,PnMg,PnMgT,ProbenNrPseud,Teilprobe,MatrixGr,MatrixGrT,Matrix,MatrixT,ZerlMatrix,...,NormCCA,NormCCB,NormME,NormMET,NormBezMe,NormBezMeT,Methode,MethodeT,Probenvorbereitung,ProbenvorbereitungT
0,2023,11,Monitoring-Planprobe,1,2,840000,Kosmetische Mittel und Stoffe zu deren Herstel...,841512,Zahnreinigungspulver/-salz,NaN,...,NaN,NaN,3,Milligramm (mg),1,Kilogramm (kg),99,Nicht in einer offiziellen Sammlung enthaltene...,NaN,NaN
1,2023,11,Monitoring-Planprobe,1,2,840000,Kosmetische Mittel und Stoffe zu deren Herstel...,841512,Zahnreinigungspulver/-salz,NaN,...,NaN,NaN,3,Milligramm (mg),1,Kilogramm (kg),99,Nicht in einer offiziellen Sammlung enthaltene...,NaN,NaN
2,2023,11,Monitoring-Planprobe,1,2,840000,Kosmetische Mittel und Stoffe zu deren Herstel...,841512,Zahnreinigungspulver/-salz,NaN,...,NaN,NaN,3,Milligramm (mg),1,Kilogramm (kg),99,Nicht in einer offiziellen Sammlung enthaltene...,NaN,NaN
3,2023,11,Monitoring-Planprobe,1,2,840000,Kosmetische Mittel und Stoffe zu deren Herstel...,841512,Zahnreinigungspulver/-salz,NaN,...,NaN,NaN,3,Milligramm (mg),1,Kilogramm (kg),99,Nicht in einer offiziellen Sammlung enthaltene...,NaN,NaN
4,2023,11,Monitoring-Planprobe,1,2,840000,Kosmetische Mittel und Stoffe zu deren Herstel...,841512,Zahnreinigungspulver/-salz,NaN,...,NaN,NaN,3,Milligramm (mg),1,Kilogramm (kg),99,Nicht in einer offiziellen Sammlung enthaltene...,NaN,NaN


In [9]:
df_sample.columns.tolist()

['Jahr',
 'PnMg',
 'PnMgT',
 'ProbenNrPseud',
 'Teilprobe',
 'MatrixGr',
 'MatrixGrT',
 'Matrix',
 'MatrixT',
 'ZerlMatrix',
 'ZerlMatrixT',
 'ZusA',
 'ZusAT',
 'Betriebsart',
 'BetriebsartT',
 'PNDat',
 'HerkStaat',
 'HerkStaatT',
 'Verarbeitung',
 'VerarbeitungT',
 'Verpackung',
 'VerpackungT',
 'Bestandteil',
 'BestandteilT',
 'Alter',
 'Fettgehalt',
 'Parameter',
 'ParameterT1',
 'ParameterT2',
 'ErgKng',
 'BezParameter',
 'BezParameterT',
 'ErgAlpha',
 'ErgAlphaT',
 'Bewertung',
 'BewertungT',
 'NormMw',
 'NormBG',
 'NormNG',
 'NormCCA',
 'NormCCB',
 'NormME',
 'NormMET',
 'NormBezMe',
 'NormBezMeT',
 'Methode',
 'MethodeT',
 'Probenvorbereitung',
 'ProbenvorbereitungT']

In [10]:
for column in df_sample.columns:
    print(f"{column}: {df_sample[column].dropna().unique()[:5]}")

Jahr: [2023]
PnMg: [11]
PnMgT: <StringArray>
['Monitoring-Planprobe']
Length: 1, dtype: str
ProbenNrPseud: [1]
Teilprobe: [2]
MatrixGr: [840000]
MatrixGrT: <StringArray>
['Kosmetische Mittel und Stoffe zu deren Herstellung']
Length: 1, dtype: str
Matrix: [841512]
MatrixT: <StringArray>
['Zahnreinigungspulver/-salz']
Length: 1, dtype: str
ZerlMatrix: []
ZerlMatrixT: []
ZusA: [99]
ZusAT: <StringArray>
['Keine Angabe']
Length: 1, dtype: str
Betriebsart: [4010100]
BetriebsartT: <StringArray>
['Lebensmittelgeschäft und (eigenständige) -verkaufsabteilung (incl. Supermarkt)']
Length: 1, dtype: str
PNDat: <StringArray>
['12JUL2023:00:00:00']
Length: 1, dtype: str
HerkStaat: [998]
HerkStaatT: <StringArray>
['Ungeklärt']
Length: 1, dtype: str
Verarbeitung: [999]
VerarbeitungT: <StringArray>
['Keine Angabe']
Length: 1, dtype: str
Verpackung: [999]
VerpackungT: <StringArray>
['Keine Angabe']
Length: 1, dtype: str
Bestandteil: [1]
BestandteilT: <StringArray>
['Gesamt/alle Bestandteile']
Length: 1, 

# Dataset Variables and English Interpretation

The dataset used in this project originates from the German **Bundesamt für Verbraucherschutz und Lebensmittelsicherheit (BVL)** (**Federal Office of Consumer Protection and Food Safety**).

The original dataset contains German variable names, category labels, and technical terminology. To preserve the structure and authenticity of the original BVL data, the German names will **not be replaced** in the DataFrame.

However, because a good part of the audience of this project is English-speaking, every German term used in the documentation, analysis, tables, and visualisations will be accompanied by its English interpretation in parentheses.

For example:

- "Bewertung" (Assessment)
- "BewertungT" (Assessment Description)
- "MatrixGrT" (Matrix Group Description)
- "HerkStaatT" (Country of Origin Description)
- "Keine Angabe" (No information provided)
- "Keine Festlegung" (No determination)
- "Ungeklärt" (Unresolved/Unknown)
- "Monitoring-Planprobe" (Monitoring planned sample)

---

## Variable Overview

| Original BVL Column | English Interpretation | Description |
|---|---|---|
| "Jahr" | Year | Year of the dataset or examination |
| "PnMg" | Sampling Programme Code | Numerical code identifying the sampling or monitoring programme |
| "PnMgT" | Sampling Programme Description | Text description of the sampling or monitoring programme, e.g. "Monitoring-Planprobe" (Monitoring planned sample) |
| "ProbenNrPseud" | Pseudonymised Sample Number | Pseudonymised identification number assigned to the sample |
| "Teilprobe" | Subsample | Identification or number of a subsample |
| "MatrixGr" | Matrix Group Code | Numerical code representing the higher-level matrix or product group |
| "MatrixGrT" | Matrix Group Description | Text description of the higher-level matrix or product group |
| "Matrix" | Matrix Code | Numerical code representing the examined matrix or product |
| "MatrixT" | Matrix Description | Text description of the examined matrix or product |
| "ZerlMatrix" | Decomposed Matrix Code | Code representing a further breakdown of the matrix; exact technical meaning will be verified using BVL documentation |
| "ZerlMatrixT" | Decomposed Matrix Description | Text description corresponding to "ZerlMatrix" (Decomposed Matrix Code) |
| "ZusA" | Additional Information Code | Code representing additional information about the sample |
| "ZusAT" | Additional Information Description | Text description of additional information, e.g. "Keine Angabe" (No information provided) |
| "Betriebsart" | Business Type Code | Numerical code representing the type of business from which the sample originated |
| "BetriebsartT" | Business Type Description | Text description of the business type |
| "PNDat" | Sampling Date | Date on which the sample was collected |
| "HerkStaat" | Country of Origin Code | Numerical code representing the country of origin |
| "HerkStaatT" | Country of Origin Description | Country from which the sample or product originated, e.g. "Ungeklärt" (Unresolved/Unknown) |
| "Verarbeitung" | Processing Code | Code representing the processing condition or state of the sample or product |
| "VerarbeitungT" | Processing Description | Text description of the processing condition or state |
| "Verpackung" | Packaging Code | Code representing the type of packaging |
| "VerpackungT" | Packaging Description | Text description of the packaging type |
| "Bestandteil" | Component Code | Code representing the component of the sample that was examined |
| "BestandteilT" | Component Description | Description of the examined component, e.g. "Gesamt/alle Bestandteile" (Total/all components) |
| "Alter" | Age | Age information where relevant and available |
| "Fettgehalt" | Fat Content | Fat content of the sample where available |
| "Parameter" | Parameter Code | Numerical code representing the substance, analyte, or parameter being examined |
| "ParameterT1" | Parameter Description | Description of the examined substance or parameter, e.g. "Quecksilber" (Mercury), "Arsen" (Arsenic), "Nickel" (Nickel), "Cadmium" (Cadmium), and "Blei" (Lead) |
| "ParameterT2" | Additional Parameter Description | Additional description of the examined parameter where available |
| "ErgKng" | Result Identifier/Code | Code associated with the analytical result; exact meanings of the individual codes will be verified using BVL documentation |
| "BezParameter" | Reference/Related Parameter Code | Code representing a related or reference parameter; exact technical meaning will be verified using BVL documentation |
| "BezParameterT" | Reference/Related Parameter Description | Text description of the related parameter, e.g. "Angebotsform" (Form offered/Presentation form) |
| "ErgAlpha" | Result Value/Code | Numerical or coded result-related information; exact interpretation will be verified using BVL documentation |
| "ErgAlphaT" | Result Description | Text description associated with the result, e.g. "n. b.; < Bestimmungsgrenze" (Not quantifiable; below the limit of quantification) |
| "Bewertung" | Assessment Code | Numerical code representing the assessment of the analytical result |
| "BewertungT" | Assessment Description | Text description of the assessment, e.g. "Keine Festlegung" (No determination) |
| "NormMw" | Normalised Measured Value | Normalised measured value of the analytical result |
| "NormBG" | Normalised Limit of Quantification | Normalised "Bestimmungsgrenze" (Limit of Quantification) |
| "NormNG" | Normalised Limit of Detection | Normalised "Nachweisgrenze" (Limit of Detection) |
| "NormCCA" | Normalised CCA Value | Technical normalised field; exact meaning will be verified using BVL documentation |
| "NormCCB" | Normalised CCB Value | Technical normalised field; exact meaning will be verified using BVL documentation |
| "NormME" | Measurement Unit Code | Numerical code representing the measurement unit |
| "NormMET" | Measurement Unit Description | Measurement unit, e.g. "Milligramm (mg)" (Milligram (mg)) |
| "NormBezMe" | Reference Unit Code | Numerical code representing the reference measurement unit |
| "NormBezMeT" | Reference Unit Description | Reference measurement unit, e.g. "Kilogramm (kg)" (Kilogram (kg)) |
| "Methode" | Method Code | Code representing the analytical or examination method used |
| "MethodeT" | Method Description | Text description of the analytical or examination method |
| "Probenvorbereitung" | Sample Preparation Code | Code representing the sample preparation procedure where available |
| "ProbenvorbereitungT" | Sample Preparation Description | Text description of the sample preparation procedure where available |

---

## Important Observation About the Data Structure

Many BVL variables occur as **code-description pairs**. The variable containing the numerical or categorical code is often accompanied by a corresponding text variable.

Examples identified during the initial inspection include:

- "MatrixGr" (Matrix Group Code) → "MatrixGrT" (Matrix Group Description)
- "Matrix" (Matrix Code) → "MatrixT" (Matrix Description)
- "Betriebsart" (Business Type Code) → "BetriebsartT" (Business Type Description)
- "HerkStaat" (Country of Origin Code) → "HerkStaatT" (Country of Origin Description)
- "Verarbeitung" (Processing Code) → "VerarbeitungT" (Processing Description)
- "Verpackung" (Packaging Code) → "VerpackungT" (Packaging Description)
- "Bestandteil" (Component Code) → "BestandteilT" (Component Description)
- "Bewertung" (Assessment Code) → "BewertungT" (Assessment Description)
- "Methode" (Method Code) → "MethodeT" (Method Description)

This relationship will be important during data cleaning and feature selection because a numerical code and its corresponding text description may represent the same underlying information.

---

## Initial Observations From the Sample

The first inspected records include:

- "PnMgT" (Sampling Programme Description): "Monitoring-Planprobe" (Monitoring planned sample)
- "MatrixGrT" (Matrix Group Description): "Kosmetische Mittel und Stoffe zu deren Herstellung" (Cosmetic products and substances used in their manufacture)
- "MatrixT" (Matrix Description): "Zahnreinigungspulver/-salz" (Tooth-cleaning powder/salt)
- "HerkStaatT" (Country of Origin Description): "Ungeklärt" (Unresolved/Unknown)
- "ZusAT" (Additional Information Description): "Keine Angabe" (No information provided)
- "BewertungT" (Assessment Description): "Keine Festlegung" (No determination)
- "NormMET" (Measurement Unit Description): "Milligramm (mg)" (Milligram (mg))
- "NormBezMeT" (Reference Unit Description): "Kilogramm (kg)" (Kilogram (kg))

The examined "ParameterT1" (Parameter Description) values include:

- "Quecksilber Hg" (Mercury Hg)
- "Arsen As, gesamt" (Total arsenic As)
- "Nickel Ni" (Nickel Ni)
- "Cadmium Cd" (Cadmium Cd)
- "Blei Pb" (Lead Pb)

The presence of "Kosmetische Mittel und Stoffe zu deren Herstellung" (Cosmetic products and substances used in their manufacture) in the initial sample indicates that the complete dataset may contain more than conventional food-product records.

Therefore, the complete distribution of "MatrixGrT" (Matrix Group Description) and related variables must be investigated before defining the final analytical scope of the Food Safety project.

---

## Target Variable

The final target variable for **Failure-Risk Prediction** has **not yet been selected**.

Potentially relevant variables such as "Bewertung" (Assessment Code), "BewertungT" (Assessment Description), and the analytical result variables will first be examined across the complete dataset.

This investigation is necessary before deciding:

1. how "Beanstandung" (Non-compliance/Failure) should be defined;
2. which variable provides the most appropriate target;
3. how the target classes should be constructed;
4. whether the resulting target is imbalanced; and
5. which predictors can be used without introducing **Target Leakage**.

No variable will be designated as the final target until its meaning, values, distribution, and relationship with the inspection outcome have been properly investigated.

---

## Language Convention for This Project

The original German terminology of the BVL dataset will be preserved throughout the DataFrames, analysis, statistical results, visualisations, and modelling workflow.

Because a good part of the  audience is English-speaking, whenever a German word, category, variable, or technical expression is displayed or discussed, its English interpretation will be provided immediately in parentheses.

For example:

**"Matrixgruppe" (Matrix Group)**  
**"Anzahl der Proben" (Number of Samples)**  
**"Bewertung" (Assessment)**  
**"Herkunftsstaat" (Country of Origin)**  
**"Beanstandung" (Non-compliance/Failure)**

The original German values will therefore remain traceable to the BVL source while the analysis remains accessible to an English-speaking audience.

In [11]:
# Count the number of data rows without loading the full dataset into memory
with open(file_path, "r", encoding="latin1") as file:
    total_rows = sum(1 for _ in file) - 1  # subtract the header row

print(f"Total number of rows: {total_rows:,}")
print(f"Total number of columns: {len(df_sample.columns)}")

Total number of rows: 2,151,894
Total number of columns: 49


In [12]:
# Load a larger sample for initial data exploration
df_inspect = pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    nrows=100_000,
    low_memory=False
)

print(f"Inspection sample rows: {df_inspect.shape[0]:,}")
print(f"Inspection sample columns: {df_inspect.shape[1]}")

Inspection sample rows: 100,000
Inspection sample columns: 49


In [13]:
# Inspect the data types of all columns
df_inspect.dtypes

Jahr                     int64
PnMg                     int64
PnMgT                      str
ProbenNrPseud            int64
Teilprobe                int64
MatrixGr                 int64
MatrixGrT                  str
Matrix                   int64
MatrixT                    str
ZerlMatrix             float64
ZerlMatrixT            float64
ZusA                   float64
ZusAT                      str
Betriebsart              int64
BetriebsartT               str
PNDat                      str
HerkStaat                int64
HerkStaatT                 str
Verarbeitung           float64
VerarbeitungT              str
Verpackung             float64
VerpackungT                str
Bestandteil            float64
BestandteilT               str
Alter                  float64
Fettgehalt             float64
Parameter                int64
ParameterT1                str
ParameterT2                str
ErgKng                     str
BezParameter             int64
BezParameterT              str
ErgAlpha

In [14]:
# Calculate missing values across the complete dataset using chunks

missing_counts = None
total_rows_checked = 0

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    chunksize=100_000,
    low_memory=False
):
    # Count missing values in the current chunk
    chunk_missing = chunk.isnull().sum()

    if missing_counts is None:
        missing_counts = chunk_missing
    else:
        missing_counts = missing_counts.add(chunk_missing, fill_value=0)

    total_rows_checked += len(chunk)

# Create the full-dataset missing-value summary
missing_summary_full = pd.DataFrame({
    "Missing_Count": missing_counts.astype(int),
    "Missing_Percentage": (
        missing_counts / total_rows_checked * 100
    ).round(2)
})

# Keep only columns with missing values
missing_summary_full = missing_summary_full[
    missing_summary_full["Missing_Count"] > 0
].sort_values(
    by="Missing_Percentage",
    ascending=False
)

print(f"Total rows analysed: {total_rows_checked:,}")
missing_summary_full

Total rows analysed: 2,151,894


,Missing_Count,Missing_Percentage
ZerlMatrix,2151894,100.00
ZerlMatrixT,2151894,100.00
NormCCB,2149940,99.91
NormCCA,2149940,99.91
NormMw,2104057,97.78
Fettgehalt,2081940,96.75
ParameterT2,1941364,90.22
Alter,1891301,87.89
Bestandteil,954379,44.35
BestandteilT,954379,44.35


In [15]:
# Count MatrixGrT (Matrix Group Description) across the complete dataset

matrix_group_counts = {}

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["MatrixGrT"],
    chunksize=100_000,
    low_memory=False
):
    counts = chunk["MatrixGrT"].value_counts(dropna=False)

    for category, count in counts.items():
        matrix_group_counts[category] = matrix_group_counts.get(category, 0) + count

matrix_group_summary = (
    pd.Series(matrix_group_counts)
    .sort_values(ascending=False)
    .to_frame(name="Count")
)

matrix_group_summary["Percentage"] = (
    matrix_group_summary["Count"] / total_rows_checked * 100
).round(2)

matrix_group_summary

,Count,Percentage
Frischgemüse ausgenommen Rhabarber,788503,36.64
Frischobst einschließlich Rhabarber,728943,33.87
Hülsenfrüchte Ölsamen Schalenobst,114225,5.31
Kartoffeln und stärkereiche Pflanzenteile,110249,5.12
Getreide,102253,4.75
Fleisch warmblütiger Tiere auch tiefgefroren,62651,2.91
Säuglings- und Kleinkindernahrungen,45650,2.12
Gemüseerzeugn. und Gemüsezuber. ausgen. Rhabarber u. 200700 u. 201700,41448,1.93
Gewürze,39588,1.84
Getreideprodukte Backvormischungen Brotteige Massen und Teige für,29952,1.39


# Initial Data Quality and Dataset Scope Assessment

The initial inspection was extended from the small working sample to the complete dataset in order to avoid drawing conclusions from only the first 100,000 records.

The complete BVL dataset contains:

- **2,151,894 rows**
- **49 variables**

Two important full-dataset investigations were conducted at this stage:

1. an assessment of missing values across all 2,151,894 records; and
2. an assessment of the distribution of "MatrixGrT" (Matrix Group Description) across the complete dataset.

These analyses provide an initial understanding of data quality and the overall product scope of the dataset.

---

## 1. Missing-Value Assessment

Missing values were calculated across all **2,151,894 records** using chunk-based processing. This approach allowed the complete 1.17 GB dataset to be analysed without loading the entire file into memory at once.

The analysis revealed substantial differences in data completeness among the variables.

### Variables With Extremely High Missingness

Several variables contain very little or no available information:

- "ZerlMatrix" (Decomposed Matrix Code): **100.00% missing**
- "ZerlMatrixT" (Decomposed Matrix Description): **100.00% missing**
- "NormCCB" (Normalised CCB Value): **99.91% missing**
- "NormCCA" (Normalised CCA Value): **99.91% missing**
- "NormMw" (Normalised Measured Value): **97.78% missing**
- "Fettgehalt" (Fat Content): **96.75% missing**
- "ParameterT2" (Additional Parameter Description): **90.22% missing**
- "Alter" (Age): **87.89% missing**

The complete absence of information in "ZerlMatrix" (Decomposed Matrix Code) and "ZerlMatrixT" (Decomposed Matrix Description) makes these variables strong candidates for removal during the data-cleaning stage.

However, no variables are removed at this stage. Their relevance to the analytical objectives will first be considered before final cleaning decisions are made.

### Variables With Moderate Missingness

Some variables contain substantial but potentially usable information:

- "Bestandteil" (Component Code): **44.35% missing**
- "BestandteilT" (Component Description): **44.35% missing**
- "Probenvorbereitung" (Sample Preparation Code): **26.98% missing**
- "ProbenvorbereitungT" (Sample Preparation Description): **26.98% missing**

These variables require further investigation before deciding whether they should be retained, transformed, or excluded.

### Variables With Relatively Low Missingness

Several variables show comparatively small proportions of missing information:

- "NormNG" (Normalised Limit of Detection): **4.35% missing**
- "ErgAlpha" (Result Value/Code): **2.22% missing**
- "ErgAlphaT" (Result Description): **2.22% missing**
- "Verarbeitung" (Processing Code): **1.04% missing**
- "VerarbeitungT" (Processing Description): **1.04% missing**
- "ZusA" (Additional Information Code): **0.58% missing**
- "ZusAT" (Additional Information Description): **0.58% missing**
- "Verpackung" (Packaging Code): **0.55% missing**
- "VerpackungT" (Packaging Description): **0.55% missing**
- "NormBG" (Normalised Limit of Quantification): **0.13% missing**

These results indicate that missingness is concentrated heavily in specific variables rather than being uniformly distributed throughout the dataset.

### Initial Data-Quality Conclusion

The missing-value analysis identifies several important data-quality issues, particularly variables with extremely high levels of missingness.

Nevertheless, missing-value percentage alone will not determine whether a variable is removed. Decisions will also consider:

- relevance to the research questions;
- importance for defining food-safety outcomes;
- potential predictive value;
- availability of related variables; and
- risk of introducing Target Leakage.

This ensures that the later data-cleaning process is evidence-based rather than relying on an arbitrary missing-value threshold.

---

## 2. Distribution of "MatrixGrT" (Matrix Group Description)

The complete distribution of "MatrixGrT" (Matrix Group Description) was examined across all **2,151,894 records**.

This analysis was particularly important because the initial ten-row sample contained "Kosmetische Mittel und Stoffe zu deren Herstellung" (Cosmetic products and substances used in their manufacture), raising the question of whether the BVL dataset primarily contained food products.

The full-dataset analysis shows that the dataset is overwhelmingly dominated by food and agricultural product groups.

The two largest groups are:

- "Frischgemüse ausgenommen Rhabarber" (Fresh vegetables excluding rhubarb): **788,503 records (36.64%)**
- "Frischobst einschließlich Rhabarber" (Fresh fruit including rhubarb): **728,943 records (33.87%)**

Together, these two groups represent approximately **70.51% of the complete dataset**.

Other major food-related groups include:

- "Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts): **114,225 records (5.31%)**
- "Kartoffeln und stärkereiche Pflanzenteile" (Potatoes and starch-rich plant parts): **110,249 records (5.12%)**
- "Getreide" (Cereals): **102,253 records (4.75%)**
- "Fleisch warmblütiger Tiere auch tiefgefroren" (Meat from warm-blooded animals, including deep-frozen products): **62,651 records (2.91%)**
- "Säuglings- und Kleinkindernahrungen" (Infant and young-child foods): **45,650 records (2.12%)**
- "Gemüseerzeugn. und Gemüsezuber. ausgen. Rhabarber u. 200700 u. 201700" (Vegetable products and preparations, excluding rhubarb and specified categories): **41,448 records (1.93%)**
- "Gewürze" (Spices): **39,588 records (1.84%)**
- "Getreideprodukte Backvormischungen Brotteige Massen und Teige für" (Cereal products, baking premixes, bread doughs, mixtures and doughs): **29,952 records (1.39%)**
- "Obstprodukte ausgenommen 310000 und 410000 einschl. Rhabarber" (Fruit products excluding specified categories, including rhubarb): **28,426 records (1.32%)**
- "Fischerzeugnisse" (Fish products): **15,276 records (0.71%)**

Smaller food-related categories include "Käse" (Cheese), "Milch" (Milk), "Tees und teeähnliche Erzeugnisse" (Tea and tea-like products), and "Süßwaren ausgenommen 440000" (Confectionery excluding category 440000).

---

## 3. Presence of Non-Food Product Groups

Although food products dominate the dataset, several non-food categories are also present.

Examples include:

- "Bedarfsgegenstände mit Lebensmittelkontakt (BgLm)" (Consumer products/materials intended for food contact): **10,354 records (0.48%)**
- "Kosmetische Mittel und Stoffe zu deren Herstellung" (Cosmetic products and substances used in their manufacture): **9,472 records (0.44%)**
- "Spielwaren und Scherzartikel" (Toys and novelty articles): **6,446 records (0.30%)**
- "Bedarfsgegenstände mit Körperkontakt und zur Körperpflege" (Consumer products intended for body contact and personal care): **334 records (0.02%)**

This explains why the initial ten-row sample contained cosmetic-product records.

The first ten rows were therefore useful for understanding the dataset structure, but they were **not representative of the overall product distribution**.

---

## 4. Implication for the Food Safety Project

The full-dataset distribution provides strong support for using this BVL dataset for the **Food Safety Inspection Analytics & Failure-Risk Prediction** project.

Fresh vegetables and fresh fruit alone account for approximately **70.51%** of all records, while numerous additional categories represent cereals, meat, fish, infant food, spices, dairy products, and other food products.

However, because a small proportion of records represents cosmetics, toys, body-contact products, and other non-food categories, the analytical population must be defined carefully before modelling.

A final decision on which "MatrixGrT" (Matrix Group Description) categories should be classified as food-related will therefore be made during the data-cleaning and scope-definition stage.

This prevents non-food records from unintentionally influencing a predictive model intended specifically to analyse **food-safety failure risk**.

---

## Current Conclusion

The initial full-dataset assessment establishes three important findings:

1. The dataset is large, containing **2,151,894 records and 49 variables**.
2. Missing data are heavily concentrated in a limited number of variables, while many other variables have relatively high completeness.
3. The dataset is predominantly food-related, with "Frischgemüse ausgenommen Rhabarber" (Fresh vegetables excluding rhubarb) and "Frischobst einschließlich Rhabarber" (Fresh fruit including rhubarb) accounting for approximately **70.51%** of all records.

These findings provide the basis for the next stage of data inspection, where the outcome-related variables will be investigated before defining the final analytical population and the target variable for Failure-Risk Prediction.

In [16]:
# Count BewertungT (Assessment Description) across the complete dataset

assessment_counts = {}

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["BewertungT"],
    chunksize=100_000,
    low_memory=False
):
    counts = chunk["BewertungT"].value_counts(dropna=False)

    for category, count in counts.items():
        assessment_counts[category] = assessment_counts.get(category, 0) + count

assessment_summary = (
    pd.Series(assessment_counts)
    .sort_values(ascending=False)
    .to_frame(name="Count")
)

assessment_summary["Percentage"] = (
    assessment_summary["Count"] / total_rows_checked * 100
).round(2)

assessment_summary

,Count,Percentage
< Höchstmenge,1796282,83.47
Stoffnachweis ist bei der entsprechenden Summe zu bewerten.,169917,7.90
Ohne Beanstandung,120956,5.62
Keine Festlegung,52854,2.46
Kein Beurteilungswert festgelegt,7658,0.36
< Grenzwert,1686,0.08
Standard erfüllt,1507,0.07
< Richtwert,360,0.02
< Auslösewert,213,0.01
< Höchstwert,153,0.01


# Assessment Outcome Distribution

The distribution of "BewertungT" (Assessment Description) was examined across the complete dataset of **2,151,894 records** to investigate whether this variable could contribute to defining the target for Failure-Risk Prediction.

The analysis shows that "BewertungT" (Assessment Description) is highly concentrated in a small number of assessment categories.

The most frequent assessment is:

- "< Höchstmenge" (Below maximum permitted level): **1,796,282 records (83.47%)**

This indicates that the large majority of analytical records with this assessment fall below the applicable maximum permitted level.

The next most frequent categories are:

- "Stoffnachweis ist bei der entsprechenden Summe zu bewerten." (Detection of the substance must be assessed using the corresponding sum): **169,917 records (7.90%)**
- "Ohne Beanstandung" (Without objection/Compliant): **120,956 records (5.62%)**
- "Keine Festlegung" (No determination): **52,854 records (2.46%)**
- "Kein Beurteilungswert festgelegt" (No assessment value established): **7,658 records (0.36%)**

Several additional categories indicate that a limit, guideline value, or standard was satisfied, including:

- "< Grenzwert" (Below limit value): **1,686 records (0.08%)**
- "Standard erfüllt" (Standard met): **1,507 records (0.07%)**
- "< Richtwert" (Below guideline value): **360 records (0.02%)**
- "< Auslösewert" (Below action level): **213 records (0.01%)**
- "< Höchstwert" (Below maximum value): **153 records (0.01%)**

---

## Potential Adverse Assessment Outcomes

The dataset also contains assessment categories that may indicate non-compliance or an unfavourable inspection outcome.

These include:

- "> Höchstmenge (führt zur Beanstandung)" (Above maximum permitted level, leading to non-compliance): **80 records**
- "Beanstandet" (Non-compliant/Objected): **50 records**
- "Standard nicht erfüllt" (Standard not met): **24 records**
- "> Richtwert" (Above guideline value): **4 records**
- "> Grenzwert" (Above limit value): **2 records**
- "> Höchstwert" (Above maximum value): **1 record**

However, exceeding a numerical value does not automatically represent the same regulatory outcome in every category.

For example:

- "> Höchstmenge (ohne Beanstandung)" (Above maximum permitted level, without non-compliance): **123 records**

This distinction is particularly important because it shows that an analytical value exceeding a stated level cannot automatically be labelled as a failure without considering the corresponding BVL assessment.

---

## Implication for Target Definition

The distribution of "BewertungT" (Assessment Description) provides useful information for the Failure-Risk Prediction objective, but a binary target should **not yet be created solely from these labels**.

Three issues require further investigation.

First, the assessment distribution is extremely imbalanced. Explicit adverse assessment categories represent only a very small fraction of the more than 2.15 million analytical records.

Second, some categories describe analytical or regulatory conditions rather than a simple compliant/non-compliant outcome. For example, "Stoffnachweis ist bei der entsprechenden Summe zu bewerten." (Detection of the substance must be assessed using the corresponding sum) does not by itself provide a straightforward failure classification.

Third, some apparently similar categories have different regulatory meanings. For example, "> Höchstmenge (ohne Beanstandung)" (Above maximum permitted level, without non-compliance) must be distinguished from "> Höchstmenge (führt zur Beanstandung)" (Above maximum permitted level, leading to non-compliance).

Therefore, the meaning and structure of "Bewertung" (Assessment Code) and "BewertungT" (Assessment Description) must be investigated further before constructing the final target variable.

---

## Current Interpretation

This analysis provides evidence that "BewertungT" (Assessment Description) contains potentially valuable outcome information for the project.

However, the results also demonstrate that **Failure-Risk Prediction cannot simply be defined as "above a limit = failure."**

The eventual target definition must distinguish between:

- compliant or acceptable assessments;
- explicit non-compliance assessments;
- assessments requiring additional interpretation; and
- records for which no assessment value or determination is available.

This distinction will help ensure that the target variable represents a meaningful food-safety outcome and reduces the risk of incorrectly labelling observations during the modelling stage.

In [17]:
# Examine Bewertung (Assessment Code) together with
# BewertungT (Assessment Description) across the complete dataset

assessment_pair_counts = {}

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["Bewertung", "BewertungT"],
    chunksize=100_000,
    low_memory=False
):
    counts = (
        chunk.groupby(
            ["Bewertung", "BewertungT"],
            dropna=False
        )
        .size()
    )

    for pair, count in counts.items():
        assessment_pair_counts[pair] = (
            assessment_pair_counts.get(pair, 0) + count
        )

assessment_pair_summary = (
    pd.Series(assessment_pair_counts)
    .sort_values(ascending=False)
    .reset_index()
)

assessment_pair_summary.columns = [
    "Bewertung (Assessment Code)",
    "BewertungT (Assessment Description)",
    "Count"
]

assessment_pair_summary["Percentage"] = (
    assessment_pair_summary["Count"]
    / total_rows_checked
    * 100
).round(4)

assessment_pair_summary

,Bewertung (Assessment Code),BewertungT (Assessment Description),Count,Percentage
0,10,< Höchstmenge,1796282,83.4745
1,49,Stoffnachweis ist bei der entsprechenden Summe...,169917,7.8962
2,72,Ohne Beanstandung,120956,5.6209
3,99,Keine Festlegung,52854,2.4562
4,98,Kein Beurteilungswert festgelegt,7658,0.3559
5,30,< Grenzwert,1686,0.0783
6,70,Standard erfüllt,1507,0.0700
7,20,< Richtwert,360,0.0167
8,22,< Auslösewert,213,0.0099
9,15,< Höchstwert,153,0.0071


# Relationship Between Assessment Codes and Assessment Descriptions

To better understand the assessment structure of the BVL dataset, "Bewertung" (Assessment Code) and "BewertungT" (Assessment Description) were analysed together across all **2,151,894 records**.

The analysis confirms that the numerical values in "Bewertung" (Assessment Code) correspond to specific textual assessment categories in "BewertungT" (Assessment Description).

This code-description relationship is important because it allows the original numerical BVL assessment codes to be interpreted correctly before defining the target variable for Failure-Risk Prediction.

---

## Main Assessment Code-Description Relationships

The most frequently occurring assessment combinations are:

| "Bewertung" (Assessment Code) | "BewertungT" (Assessment Description) | Count | Percentage |
|---:|---|---:|---:|
| 10 | "< Höchstmenge" (Below maximum permitted level) | 1,796,282 | 83.4745% |
| 49 | "Stoffnachweis ist bei der entsprechenden Summe zu bewerten." (Detection of the substance must be assessed using the corresponding sum) | 169,917 | 7.8962% |
| 72 | "Ohne Beanstandung" (Without objection/Compliant) | 120,956 | 5.6209% |
| 99 | "Keine Festlegung" (No determination) | 52,854 | 2.4562% |
| 98 | "Kein Beurteilungswert festgelegt" (No assessment value established) | 7,658 | 0.3559% |
| 30 | "< Grenzwert" (Below limit value) | 1,686 | 0.0783% |
| 70 | "Standard erfüllt" (Standard met) | 1,507 | 0.0700% |
| 20 | "< Richtwert" (Below guideline value) | 360 | 0.0167% |
| 22 | "< Auslösewert" (Below action level) | 213 | 0.0099% |
| 15 | "< Höchstwert" (Below maximum value) | 153 | 0.0071% |

The dominant assessment is therefore code **10**, "< Höchstmenge" (Below maximum permitted level), representing approximately **83.47%** of all records.

---

## Potential Non-Compliance Assessment Codes

Several assessment codes appear particularly relevant to the Failure-Risk Prediction objective:

| "Bewertung" (Assessment Code) | "BewertungT" (Assessment Description) | Count | Percentage |
|---:|---|---:|---:|
| 12 | "> Höchstmenge (führt zur Beanstandung)" (Above maximum permitted level, leading to non-compliance) | 80 | 0.0037% |
| 73 | "Beanstandet" (Non-compliant/Objected) | 50 | 0.0023% |
| 71 | "Standard nicht erfüllt" (Standard not met) | 24 | 0.0011% |
| 21 | "> Richtwert" (Above guideline value) | 4 | 0.0002% |
| 31 | "> Grenzwert" (Above limit value) | 2 | 0.0001% |
| 16 | "> Höchstwert" (Above maximum value) | 1 | Less than 0.0001% |

These categories require careful interpretation before they are combined into a single failure class.

---

## Important Regulatory Distinction

The assessment codes demonstrate that exceeding a numerical level does **not automatically mean that a record was classified as non-compliant**.

For example:

- Code **11**: "> Höchstmenge (ohne Beanstandung)" (Above maximum permitted level, without non-compliance) — **123 records**
- Code **12**: "> Höchstmenge (führt zur Beanstandung)" (Above maximum permitted level, leading to non-compliance) — **80 records**

These two categories appear numerically similar because both indicate values above a maximum permitted level. However, their assessment outcomes are explicitly different.

This distinction is important for the project because simply classifying every value above a threshold as a failure could incorrectly label some observations.

---

## Implications for Failure-Risk Prediction

The combined analysis of "Bewertung" (Assessment Code) and "BewertungT" (Assessment Description) provides a stronger basis for defining the future target variable.

However, the target will **not yet be constructed**.

Before creating a binary outcome such as:

**0 = Compliant / Acceptable**

and

**1 = Non-compliant / Failure**

the assessment categories must be separated into at least three conceptual groups:

**Clearly acceptable outcomes**, such as "< Höchstmenge" (Below maximum permitted level), "Ohne Beanstandung" (Without objection/Compliant), and "Standard erfüllt" (Standard met).

**Clearly adverse outcomes**, such as "> Höchstmenge (führt zur Beanstandung)" (Above maximum permitted level, leading to non-compliance), "Beanstandet" (Non-compliant/Objected), and "Standard nicht erfüllt" (Standard not met).

**Ambiguous or non-classifiable outcomes**, such as "Keine Festlegung" (No determination), "Kein Beurteilungswert festgelegt" (No assessment value established), and "Stoffnachweis ist bei der entsprechenden Summe zu bewerten." (Detection of the substance must be assessed using the corresponding sum).

These distinctions should be investigated further before the final target definition is established.

---

## Current Conclusion

The analysis confirms that "Bewertung" (Assessment Code) and "BewertungT" (Assessment Description) provide structured information about the assessment outcome of individual analytical records.

At the same time, explicit adverse assessments are **extremely rare compared with acceptable assessments**.

This indicates that if these categories are eventually used to construct the Failure-Risk Prediction target, the resulting classification problem may be **highly imbalanced**.

Therefore, later modelling should not rely on accuracy alone. Appropriate classification metrics and potential class-imbalance strategies will need to be considered after the final target population and target definition have been established.

For now, the evidence supports continuing the investigation of the assessment structure before constructing the predictive target.

In [18]:
# Count PnMgT (Sampling Programme Description)
# across the complete dataset

sampling_program_counts = {}

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["PnMgT"],
    chunksize=100_000,
    low_memory=False
):
    counts = chunk["PnMgT"].value_counts(dropna=False)

    for category, count in counts.items():
        sampling_program_counts[category] = (
            sampling_program_counts.get(category, 0) + count
        )

sampling_program_summary = (
    pd.Series(sampling_program_counts)
    .sort_values(ascending=False)
    .to_frame(name="Count")
)

sampling_program_summary["Percentage"] = (
    sampling_program_summary["Count"]
    / total_rows_checked
    * 100
).round(2)

sampling_program_summary

,Count,Percentage
Monitoring-Planprobe,1328165,61.72
EG(KKP)- und Monitoring-Planprobe,821113,38.16
Monitoring-Projektprobe,2616,0.12


# Sampling Programme Distribution

The distribution of "PnMgT" (Sampling Programme Description) was examined across the complete dataset of **2,151,894 records**.

The purpose of this analysis was to understand how the samples in the BVL dataset were collected and whether different sampling programmes are represented in the data.

Three sampling-programme categories were identified:

| "PnMgT" (Sampling Programme Description) | Count | Percentage |
|---|---:|---:|
| "Monitoring-Planprobe" (Monitoring planned sample) | 1,328,165 | 61.72% |
| "EG(KKP)- und Monitoring-Planprobe" (EC/KP and monitoring planned sample) | 821,113 | 38.16% |
| "Monitoring-Projektprobe" (Monitoring project sample) | 2,616 | 0.12% |

---

## Interpretation

The largest sampling category is "Monitoring-Planprobe" (Monitoring planned sample), accounting for **61.72%** of all analytical records.

The second major category is "EG(KKP)- und Monitoring-Planprobe" (EC/KP and monitoring planned sample), which represents **38.16%** of the dataset.

Together, these two categories account for approximately **99.88%** of all records.

"Monitoring-Projektprobe" (Monitoring project sample) represents only **0.12%** of the dataset.

This indicates that the dataset is overwhelmingly composed of records associated with planned monitoring activities rather than project-specific monitoring samples.

---

## Implication for the Analysis

The presence of multiple sampling programmes is important because the sampling programme may be associated with differences in the types of products, substances, or analytical assessments represented in the dataset.

At this stage, no sampling programme will be excluded.

"PnMgT" (Sampling Programme Description) may later be investigated as a potential explanatory variable when analysing patterns in food-safety assessments.

However, its relationship with the eventual target variable must be evaluated carefully before it is used as a predictor in the Failure-Risk Prediction model.

The very small size of the "Monitoring-Projektprobe" (Monitoring project sample) category should also be considered during later exploratory analysis because it represents only **0.12%** of the complete dataset.

---

## Current Conclusion

The complete BVL dataset contains three sampling-programme categories, but approximately **99.88%** of all analytical records belong to the two main planned-monitoring categories.

This confirms that sampling programme information is available across the dataset and provides an additional characteristic that can be investigated during later exploratory analysis and feature selection.

In [19]:
   # Count the number of unique ParameterT1 (Parameter Description)
# values across the complete dataset

unique_parameters = set()

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["ParameterT1"],
    chunksize=100_000,
    low_memory=False
):
    unique_parameters.update(
        chunk["ParameterT1"].dropna().unique()
    )

print(
    f"Number of unique ParameterT1 "
    f"(Parameter Description) values: {len(unique_parameters):,}"
)

Number of unique ParameterT1 (Parameter Description) values: 1,244


In [20]:
# Count ParameterT1 (Parameter Description)
# across the complete dataset

parameter_counts = {}

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["ParameterT1"],
    chunksize=100_000,
    low_memory=False
):
    counts = chunk["ParameterT1"].value_counts(dropna=False)

    for parameter, count in counts.items():
        parameter_counts[parameter] = (
            parameter_counts.get(parameter, 0) + count
        )

parameter_summary = (
    pd.Series(parameter_counts)
    .sort_values(ascending=False)
    .to_frame(name="Count")
)

parameter_summary["Percentage"] = (
    parameter_summary["Count"]
    / total_rows_checked
    * 100
).round(2)

# Display only the 20 most frequent parameters
parameter_summary.head(20)

,Count,Percentage
beta-Endosulfan,4343,0.2
alpha-Endosulfan,4343,0.2
Dieldrin,4343,0.2
Lindan; gamma-Hexachlorcyclohexan; gamma-HCH,4340,0.2
Endosulfan-sulfat,4333,0.2
Aldrin,4322,0.2
Pendimethalin,4315,0.2
Diazinon,4315,0.2
Bifenthrin,4313,0.2
Chlorpyrifos-methyl,4310,0.2


# Analytical Parameter Distribution

The variable "ParameterT1" (Parameter Description) was examined across the complete BVL dataset to understand which substances and analytical parameters were tested.

A total of **1,244 unique values** were identified in "ParameterT1" (Parameter Description).

Because of this large number of unique analytical parameters, displaying all categories would not provide a useful overview. Therefore, the 20 most frequently occurring parameters were examined first.

---

## Most Frequently Recorded Analytical Parameters

The most frequently occurring "ParameterT1" (Parameter Description) values include:

| "ParameterT1" (Parameter Description) | Count | Percentage |
|---|---:|---:|
| "beta-Endosulfan" (Beta-endosulfan) | 4,343 | 0.20% |
| "alpha-Endosulfan" (Alpha-endosulfan) | 4,343 | 0.20% |
| "Dieldrin" (Dieldrin) | 4,343 | 0.20% |
| "Lindan; gamma-Hexachlorcyclohexan; gamma-HCH" (Lindane; gamma-hexachlorocyclohexane; gamma-HCH) | 4,340 | 0.20% |
| "Endosulfan-sulfat" (Endosulfan sulfate) | 4,333 | 0.20% |
| "Aldrin" (Aldrin) | 4,322 | 0.20% |
| "Pendimethalin" (Pendimethalin) | 4,315 | 0.20% |
| "Diazinon" (Diazinon) | 4,315 | 0.20% |
| "Bifenthrin" (Bifenthrin) | 4,313 | 0.20% |
| "Chlorpyrifos-methyl" (Chlorpyrifos-methyl) | 4,310 | 0.20% |
| "Parathion" (Parathion) | 4,310 | 0.20% |
| "Triazophos" (Triazophos) | 4,310 | 0.20% |
| "Chlorpyrifos" (Chlorpyrifos) | 4,309 | 0.20% |
| "Tetraconazol" (Tetraconazole) | 4,303 | 0.20% |
| "Parathion-methyl" (Parathion-methyl) | 4,303 | 0.20% |
| "Permethrin, Gesamt-, Summe der Isomeren" (Permethrin, total, sum of isomers) | 4,302 | 0.20% |
| "Deltamethrin" (Deltamethrin) | 4,298 | 0.20% |
| "Pyrazophos" (Pyrazophos) | 4,296 | 0.20% |
| "Methoxychlor" (Methoxychlor) | 4,295 | 0.20% |
| "Cypermethrin, Gesamt-, Summe der Isomere, ausgedrückt als Cypermethrin" (Cypermethrin, total, sum of isomers expressed as cypermethrin) | 4,294 | 0.20% |

---

## Interpretation

The most frequently recorded analytical parameters are predominantly pesticide-related substances.

However, no single parameter dominates the dataset. Even the most frequently occurring parameters each account for only approximately **0.20%** of the complete dataset.

Together with the identification of **1,244 unique parameters**, this indicates that the BVL monitoring data contain a broad range of analytical tests rather than being concentrated on only a small number of substances.

This diversity is important for the project because different food products may be tested for different substances and may therefore have different patterns of analytical assessment.

---

## Important Observation About the Dataset Structure

The large number of analytical parameters also reinforces an important interpretation of the dataset.

The **2,151,894 rows do not represent 2,151,894 individual food businesses or necessarily 2,151,894 independent food samples**.

A single sample may be analysed for multiple substances or parameters. Each analytical determination can therefore contribute a separate row to the dataset.

Consequently, the number of analytical records must be distinguished from the number of unique physical samples.

The pseudonymised sample identifier "ProbenNrPseud" (Pseudonymised Sample Number) will later be investigated to determine how many unique samples are represented in the dataset.

---

## Implication for Failure-Risk Prediction

The high cardinality of "ParameterT1" (Parameter Description), with **1,244 unique categories**, will require careful consideration during feature engineering.

Directly one-hot encoding all 1,244 parameter categories may create a large number of model features.

Possible strategies may later include grouping parameters into meaningful analytical categories, using the associated "Parameter" (Parameter Code), retaining only appropriately supported categories, or applying another suitable encoding strategy.

No such transformation will be performed at this stage.

The appropriate approach will be determined after the analytical population, target variable, and relationships between parameters and assessment outcomes have been investigated.

In [21]:
# Count unique ProbenNrPseud (Pseudonymised Sample Number)
# across the complete dataset

unique_samples = set()

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["ProbenNrPseud"],
    chunksize=100_000,
    low_memory=False
):
    unique_samples.update(
        chunk["ProbenNrPseud"].dropna().unique()
    )

print(
    f"Number of unique ProbenNrPseud "
    f"(Pseudonymised Sample Number) values: {len(unique_samples):,}"
)

Number of unique ProbenNrPseud (Pseudonymised Sample Number) values: 9,711


# Number of Unique Samples

The complete BVL dataset contains **2,151,894 analytical records**, but only **9,711 unique values** of "ProbenNrPseud" (Pseudonymised Sample Number).

This is an important distinction because each row in the dataset does not represent a separate physical food sample.

On average:

**2,151,894 analytical records / 9,711 unique samples ≈ 221.6 analytical records per sample**

Therefore, an individual sample is associated with many analytical records, which is consistent with samples being tested for multiple "ParameterT1" (Parameter Description) substances.

## Implication for the Project

The dataset must be treated as containing at least two important levels of information:

- **Sample level:** represented by "ProbenNrPseud" (Pseudonymised Sample Number).
- **Analytical-result level:** individual records representing tests or determinations associated with those samples.

This distinction is particularly important for machine learning.

Before defining the final target variable, it must be decided whether the project will predict:

**1. Analytical-result-level failure:**  
Whether an individual analytical determination is non-compliant.

or

**2. Sample-level failure:**  
Whether a food sample has at least one analytical result that leads to non-compliance.

The appropriate unit of analysis will be determined after examining how assessment outcomes are distributed within individual samples.

No aggregation will be performed yet.

In [23]:
# Count unique combinations of:
# ProbenNrPseud (Pseudonymised Sample Number)
# + Teilprobe (Subsample)

sample_subsample_pairs = set()

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["ProbenNrPseud", "Teilprobe"],
    chunksize=100_000,
    low_memory=False
):
    pairs = chunk[
        ["ProbenNrPseud", "Teilprobe"]
    ].drop_duplicates()

    sample_subsample_pairs.update(
        map(tuple, pairs.to_numpy())
    )

print(
    f"Number of unique ProbenNrPseud + Teilprobe "
    f"(Sample + Subsample) combinations: "
    f"{len(sample_subsample_pairs):,}"
)

Number of unique ProbenNrPseud + Teilprobe (Sample + Subsample) combinations: 10,986


# Sample and Subsample Structure

The complete dataset contains:

- **9,711 unique "ProbenNrPseud" (Pseudonymised Sample Number) values**
- **10,986 unique combinations of "ProbenNrPseud" (Pseudonymised Sample Number) and "Teilprobe" (Subsample)**

The number of sample–subsample combinations is therefore greater than the number of unique pseudonymised sample numbers.

This confirms that some samples are associated with more than one "Teilprobe" (Subsample).

## Dataset Hierarchy

The current analysis indicates that the BVL dataset has a hierarchical structure:

**Sample → Subsample → Analytical Parameter/Result**

A "ProbenNrPseud" (Pseudonymised Sample Number) may contain one or more "Teilprobe" (Subsample) records, while each sample or subsample can be associated with many analytical parameters.

This helps explain why the dataset contains **2,151,894 analytical records** despite having only **9,711 unique pseudonymised sample numbers**.

## Implication for Machine Learning

This structure is important for defining the unit of analysis and preventing data leakage.

If records belonging to the same sample are randomly divided between training and test datasets, information from the same underlying sample could potentially appear in both sets.

Therefore, the final train-test splitting strategy must take the sample structure into consideration.

The final prediction level — analytical-result level, subsample level, or sample level — will be determined after further investigation of the assessment outcomes.

No aggregation is performed at this stage.

In [24]:
# Number of unique Teilprobe (Subsample) values
# associated with each ProbenNrPseud (Pseudonymised Sample Number)

sample_subsample_counts = {}

for sample_id, subsample in sample_subsample_pairs:
    if sample_id not in sample_subsample_counts:
        sample_subsample_counts[sample_id] = set()

    sample_subsample_counts[sample_id].add(subsample)

subsamples_per_sample = pd.Series(
    {
        sample_id: len(subsamples)
        for sample_id, subsamples in sample_subsample_counts.items()
    }
)

print("Distribution of subsamples per sample:")
print(subsamples_per_sample.value_counts().sort_index())

print(
    "\nMaximum number of subsamples for one sample:",
    subsamples_per_sample.max()
)

Distribution of subsamples per sample:
1     9235
2      147
3      151
4       34
5       10
6      129
7        1
8        2
9        1
12       1
Name: count, dtype: int64

Maximum number of subsamples for one sample: 12


# Distribution of Subsamples per Sample

The relationship between "ProbenNrPseud" (Pseudonymised Sample Number) and "Teilprobe" (Subsample) was further examined.

| Number of "Teilprobe" (Subsamples) | Number of Samples |
|---:|---:|
| 1 | 9,235 |
| 2 | 147 |
| 3 | 151 |
| 4 | 34 |
| 5 | 10 |
| 6 | 129 |
| 7 | 1 |
| 8 | 2 |
| 9 | 1 |
| 12 | 1 |

The maximum number of "Teilprobe" (Subsamples) associated with a single sample is **12**.

## Interpretation

Of the **9,711 unique "ProbenNrPseud" (Pseudonymised Sample Number) values**, **9,235 samples (approximately 95.1%)** are associated with only one "Teilprobe" (Subsample).

Only **476 samples (approximately 4.9%)** contain more than one subsample.

Therefore, although a subsample level exists in the structure of the BVL dataset, the great majority of samples contain only one subsample.

An interesting pattern is that **129 samples contain exactly six subsamples**. This may reflect a particular sampling or analytical procedure, but its meaning should not be assumed without further evidence.

## Current Understanding of the Data Structure

The analysis currently indicates the following hierarchy:

**9,711 Samples → 10,986 Sample–Subsample Combinations → 2,151,894 Analytical Records**

This demonstrates that the very large number of rows is primarily caused by multiple analytical determinations being performed on samples and subsamples rather than by millions of independent food samples.

## Machine-Learning Implication

The hierarchical structure must be considered when constructing the predictive model.

Records belonging to the same "ProbenNrPseud" (Pseudonymised Sample Number) should not be allowed to create information leakage between training and test datasets.

A group-aware train-test splitting or cross-validation strategy using the sample identifier may therefore be considered during the modelling stage.

The final decision will depend on whether the prediction target is defined at the analytical-result, subsample, or sample level.

In [25]:
# Identify samples containing at least one clearly adverse assessment

adverse_assessments = {
    "Beanstandet",
    "Standard nicht erfüllt",
    "> Höchstmenge (führt zur Beanstandung)"
}

all_samples = set()
adverse_samples = set()
adverse_records = 0

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["ProbenNrPseud", "BewertungT"],
    chunksize=100_000,
    low_memory=False
):
    all_samples.update(
        chunk["ProbenNrPseud"].dropna().unique()
    )

    adverse_mask = chunk["BewertungT"].isin(adverse_assessments)

    adverse_records += adverse_mask.sum()

    adverse_samples.update(
        chunk.loc[
            adverse_mask,
            "ProbenNrPseud"
        ].dropna().unique()
    )

print(f"Total unique samples: {len(all_samples):,}")
print(f"Clearly adverse analytical records: {adverse_records:,}")
print(f"Samples with at least one clearly adverse result: {len(adverse_samples):,}")

print(
    "Percentage of samples with at least one clearly adverse result: "
    f"{len(adverse_samples) / len(all_samples) * 100:.2f}%"
)

Total unique samples: 9,711
Clearly adverse analytical records: 154
Samples with at least one clearly adverse result: 93
Percentage of samples with at least one clearly adverse result: 0.96%


# Preliminary Sample-Level Non-Compliance Assessment

A conservative preliminary definition of clearly adverse assessment outcomes was used to investigate potential non-compliance at the sample level.

The following "BewertungT" (Assessment Description) categories were classified as clearly adverse:

- "Beanstandet" (Non-compliant/Objected)
- "Standard nicht erfüllt" (Standard not met)
- "> Höchstmenge (führt zur Beanstandung)" (Above maximum permitted level, leading to non-compliance)

Categories whose meaning was ambiguous or which explicitly indicated that no non-compliance occurred were not included.

## Results

Across the complete dataset:

- **9,711 unique samples** were identified.
- **154 analytical records** contained one of the clearly adverse assessment outcomes.
- **93 unique samples** contained at least one clearly adverse analytical result.
- Approximately **0.96% of all samples** contained at least one clearly adverse result.

Therefore, approximately **99.04% of samples did not contain one of the clearly adverse assessment outcomes under this preliminary definition**.

## Analytical-Level versus Sample-Level Interpretation

The dataset contains **2,151,894 analytical records**, but these records originate from only **9,711 unique samples**.

At the analytical-record level, clearly adverse outcomes are extremely rare. However, multiple analytical determinations can belong to the same sample.

Aggregating the results conceptually to the sample level shows that **93 samples contained at least one clearly adverse result**.

This makes sample-level non-compliance potentially more meaningful for the project's food-safety risk-prediction objective than treating every analytical determination as an independent observation.

## Class-Imbalance Implication

A preliminary sample-level adverse rate of **0.96%** indicates a highly imbalanced classification problem.

If the final target is defined at the sample level, standard accuracy alone would therefore be misleading.

For example, a model that predicted every sample as compliant could achieve approximately **99% accuracy while identifying none of the adverse samples**.

Consequently, model evaluation should place greater emphasis on metrics such as:

- Recall
- Precision
- F1-score
- Confusion matrix
- Precision-Recall AUC (PR-AUC)

Class-imbalance handling techniques may also be considered during modelling.

For XGBoost (Extreme Gradient Boosting), parameters designed to account for class imbalance, such as "scale_pos_weight", may later be evaluated during model tuning.

## Target Status

This analysis provides strong evidence for investigating a **sample-level binary target** representing whether a sample contains at least one clearly adverse assessment.

However, the target definition remains preliminary.

Before finalising it, the assessment categories, sample structure, potential ambiguous outcomes, and availability of predictor variables before the assessment outcome must be evaluated carefully to prevent target leakage.

In [26]:
# Examine MatrixGrT (Matrix Group Description)
# for samples containing at least one clearly adverse result

adverse_sample_groups = []

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["ProbenNrPseud", "MatrixGrT"],
    chunksize=100_000,
    low_memory=False
):
    adverse_rows = chunk[
        chunk["ProbenNrPseud"].isin(adverse_samples)
    ][["ProbenNrPseud", "MatrixGrT"]]

    adverse_sample_groups.append(adverse_rows)

adverse_sample_groups = pd.concat(
    adverse_sample_groups,
    ignore_index=True
).drop_duplicates()

adverse_group_counts = (
    adverse_sample_groups["MatrixGrT"]
    .value_counts()
)

adverse_group_counts

MatrixGrT
Kosmetische Mittel und Stoffe zu deren Herstellung                       22
Frischobst einschließlich Rhabarber                                      15
Hülsenfrüchte Ölsamen Schalenobst                                        15
Gewürze                                                                  14
Fleisch warmblütiger Tiere auch tiefgefroren                              9
Obstprodukte ausgenommen 310000 und 410000 einschl. Rhabarber             4
Getreideprodukte Backvormischungen Brotteige Massen und Teige für         3
Frischgemüse ausgenommen Rhabarber                                        3
Kartoffeln und stärkereiche Pflanzenteile                                 2
Gemüseerzeugn. und Gemüsezuber. ausgen. Rhabarber u. 200700 u. 201700     2
Getreide                                                                  2
Krusten- Schalen- Weichtiere sonstige Tiere u. Erzeugnisse daraus         1
Käse                                                                      1
Na

# Product Groups Among Samples With Clearly Adverse Results

The product-group distribution of samples containing at least one clearly adverse assessment was examined using "MatrixGrT" (Matrix Group Description).

A total of **93 samples** had previously been identified as containing at least one clearly adverse analytical result.

The largest observed groups included:

- "Kosmetische Mittel und Stoffe zu deren Herstellung" (Cosmetic products and substances used in their manufacture): **22 samples**
- "Frischobst einschließlich Rhabarber" (Fresh fruit including rhubarb): **15 samples**
- "Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts): **15 samples**
- "Gewürze" (Spices): **14 samples**
- "Fleisch warmblütiger Tiere auch tiefgefroren" (Meat from warm-blooded animals, including deep-frozen products): **9 samples**

## Important Scope Finding

The group with the largest number of clearly adverse samples is "Kosmetische Mittel und Stoffe zu deren Herstellung" (Cosmetic products and substances used in their manufacture).

This is important because the project is focused on **food safety**, while the original BVL monitoring dataset also contains some non-food product groups.

Therefore, the 93 preliminary adverse samples should not automatically be treated as the final food-safety failure population.

A clearly defined food-related analytical population must first be established before the final target prevalence is calculated.

## Important Statistical Distinction

The number of adverse samples within a product group does **not** by itself indicate that the product group has a higher failure risk.

For example, a product category may contain more adverse samples simply because substantially more samples from that category were examined.

The appropriate comparison is therefore the **group-specific adverse rate**:

**Adverse samples in product group / Total samples examined in product group**

This rate will allow product groups of different sizes to be compared more meaningfully.

## Current Conclusion

The analysis confirms that adverse outcomes occur across several product groups, but it also reveals that non-food categories contribute materially to the preliminary adverse population.

The food-safety scope should therefore be defined before the final machine-learning target and class-imbalance ratio are established.

In [27]:
# Build one Sample + Matrix Group table across the complete dataset

sample_groups = []

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=["ProbenNrPseud", "MatrixGrT"],
    chunksize=100_000,
    low_memory=False
):
    sample_groups.append(
        chunk[
            ["ProbenNrPseud", "MatrixGrT"]
        ].drop_duplicates()
    )

sample_groups = (
    pd.concat(sample_groups, ignore_index=True)
    .drop_duplicates()
)

# Mark samples that had at least one clearly adverse result
sample_groups["Adverse"] = (
    sample_groups["ProbenNrPseud"]
    .isin(adverse_samples)
)

# Calculate total samples, adverse samples and adverse rate
group_risk = (
    sample_groups
    .groupby("MatrixGrT")
    .agg(
        Total_Samples=("ProbenNrPseud", "nunique"),
        Adverse_Samples=("Adverse", "sum")
    )
)

group_risk["Adverse_Rate_Percent"] = (
    group_risk["Adverse_Samples"]
    / group_risk["Total_Samples"]
    * 100
).round(2)

group_risk.sort_values(
    "Adverse_Rate_Percent",
    ascending=False
)

,Total_Samples,Adverse_Samples,Adverse_Rate_Percent
MatrixGrT,,,
Kosmetische Mittel und Stoffe zu deren Herstellung,580,22,3.79
Gewürze,381,14,3.67
Hülsenfrüchte Ölsamen Schalenobst,922,15,1.63
Fleisch warmblütiger Tiere auch tiefgefroren,628,9,1.43
Frischobst einschließlich Rhabarber,1521,15,0.99
Obstprodukte ausgenommen 310000 und 410000 einschl. Rhabarber,523,4,0.76
Kartoffeln und stärkereiche Pflanzenteile,267,2,0.75
Gemüseerzeugn. und Gemüsezuber. ausgen. Rhabarber u. 200700 u. 201700,289,2,0.69
Getreideprodukte Backvormischungen Brotteige Massen und Teige für,550,3,0.55


# Product-Group Adverse Rates

The preliminary adverse rate was calculated for each "MatrixGrT" (Matrix Group Description) using:

**Adverse samples in the product group / Total samples in the product group × 100**

This provides a more meaningful comparison than the absolute number of adverse samples because the number of samples examined differs substantially between product groups.

## Highest Preliminary Adverse Rates

Among the food-related groups, the highest preliminary adverse rates were observed for:

| Product Group | Total Samples | Adverse Samples | Adverse Rate |
|---|---:|---:|---:|
| "Gewürze" (Spices) | 381 | 14 | 3.67% |
| "Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts) | 922 | 15 | 1.63% |
| "Fleisch warmblütiger Tiere auch tiefgefroren" (Meat from warm-blooded animals, including deep-frozen products) | 628 | 9 | 1.43% |
| "Frischobst einschließlich Rhabarber" (Fresh fruit including rhubarb) | 1,521 | 15 | 0.99% |
| "Obstprodukte ausgenommen 310000 und 410000 einschl. Rhabarber" (Fruit products excluding categories 310000 and 410000, including rhubarb) | 523 | 4 | 0.76% |
| "Kartoffeln und stärkereiche Pflanzenteile" (Potatoes and starch-rich plant parts) | 267 | 2 | 0.75% |

## Important Comparison

"Frischgemüse ausgenommen Rhabarber" (Fresh vegetables excluding rhubarb) contained the largest number of samples in the dataset, with **1,817 samples**, but only **3 clearly adverse samples**.

Its preliminary adverse rate was therefore only **0.17%**.

This demonstrates why the absolute number of adverse samples alone should not be interpreted as product risk.

## Non-Food Category

"Kosmetische Mittel und Stoffe zu deren Herstellung" (Cosmetic products and substances used in their manufacture) had:

- **580 samples**
- **22 adverse samples**
- **3.79% adverse rate**

This was the highest preliminary rate in the dataset, but cosmetics are outside the intended edible-food scope of the project.

Their inclusion would therefore substantially influence the overall failure rate and could cause the predictive model to learn patterns that are not directly relevant to food-product safety.

## Categories With No Clearly Adverse Samples

Several categories had no clearly adverse samples under the current conservative target definition.

A zero observed adverse rate does not necessarily prove that the category has no food-safety risk. It means only that no clearly adverse outcome was identified within the available 2023 monitoring samples using the current preliminary definition.

## Statistical Caution

The adverse rates must be interpreted together with the number of samples examined.

A high percentage based on a relatively small number of observations is less stable than a similar percentage based on a much larger sample.

Formal statistical comparisons may therefore be considered later during exploratory data analysis.

## Structural Finding

The product-group sample counts together account for all **9,711 unique samples**.

This supports the use of "MatrixGrT" (Matrix Group Description) as an important sample-level descriptive variable for the subsequent food-safety analysis.

## Current Conclusion

The preliminary results suggest meaningful differences in adverse rates between product groups.

In particular, "Gewürze" (Spices), "Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts), and "Fleisch warmblütiger Tiere auch tiefgefroren" (Meat from warm-blooded animals, including deep-frozen products) show higher preliminary adverse rates than several other food categories.

However, the food-only analytical population must be formally defined before these rates are treated as final project results.

In [28]:
# Define clearly non-food product groups for a provisional
# strict food-product scope

non_food_groups = {
    "Kosmetische Mittel und Stoffe zu deren Herstellung",
    "Spielwaren und Scherzartikel",
    "Bedarfsgegenstände mit Körperkontakt und zur Körperpflege",
    "Bedarfsgegenstände mit Lebensmittelkontakt (BgLm)"
}

food_scope = sample_groups[
    ~sample_groups["MatrixGrT"].isin(non_food_groups)
].copy()

food_sample_ids = set(
    food_scope["ProbenNrPseud"].unique()
)

food_adverse_samples = food_sample_ids.intersection(
    adverse_samples
)

print(f"Food-scope samples: {len(food_sample_ids):,}")
print(
    f"Food-scope samples with clearly adverse results: "
    f"{len(food_adverse_samples):,}"
)

print(
    "Food-scope adverse rate: "
    f"{len(food_adverse_samples) / len(food_sample_ids) * 100:.2f}%"
)

Food-scope samples: 8,582
Food-scope samples with clearly adverse results: 71
Food-scope adverse rate: 0.83%


# Preliminary Food-Scope Target Distribution

To align the analysis with the project's food-safety objective, clearly non-food product groups were provisionally excluded from the sample population.

The excluded groups were:

- "Kosmetische Mittel und Stoffe zu deren Herstellung" (Cosmetic products and substances used in their manufacture)
- "Spielwaren und Scherzartikel" (Toys and novelty articles)
- "Bedarfsgegenstände mit Körperkontakt und zur Körperpflege" (Consumer products intended for body contact and personal care)
- "Bedarfsgegenstände mit Lebensmittelkontakt (BgLm)" (Consumer products/materials intended for food contact)

The final decision regarding scope will remain documented and justified, but this provisional definition allows the food-only population to be evaluated separately.

## Food-Scope Results

After applying the provisional food-product scope:

- **8,582 unique food samples** remained.
- **71 samples** contained at least one clearly adverse assessment.
- **8,511 samples** did not contain a clearly adverse assessment.
- The preliminary food-scope adverse rate was **0.83%**.

## Effect of Restricting the Dataset to Food Products

Before restricting the population to food products, the complete dataset contained:

- **9,711 samples**
- **93 samples with clearly adverse results**
- **0.96% preliminary adverse rate**

After restricting the population to food products:

- **8,582 samples**
- **71 samples with clearly adverse results**
- **0.83% preliminary adverse rate**

The reduction from 93 to 71 adverse samples is primarily explained by the removal of the non-food "Kosmetische Mittel und Stoffe zu deren Herstellung" (Cosmetic products and substances used in their manufacture) category, which contained 22 clearly adverse samples.

This demonstrates why defining the analytical scope is important before constructing the final machine-learning target.

## Class-Imbalance Implication

The preliminary food-safety classification problem is highly imbalanced.

Only approximately **0.83%** of food samples belong to the adverse class, while approximately **99.17%** belong to the non-adverse class.

A model that predicts every food sample as non-adverse would therefore achieve approximately 99% accuracy while failing to identify any unsafe or non-compliant samples.

Accuracy will consequently not be used as the primary measure of model quality.

Evaluation will emphasize metrics including:

- Recall
- Precision
- F1-score
- Confusion matrix
- Precision-Recall AUC (PR-AUC)

Imbalance-handling approaches such as class weighting, SMOTE (Synthetic Minority Over-sampling Technique), and XGBoost (Extreme Gradient Boosting) imbalance parameters will later be evaluated using the training data only.

## Preliminary Target Concept

The emerging sample-level target can be conceptualised as:

**Target = 1:** the food sample contains at least one clearly adverse analytical assessment.

**Target = 0:** the food sample contains no clearly adverse analytical assessment.

This remains a preliminary target definition and will be validated further before modelling.

In [29]:
# Create preliminary sample-level target dataframe

sample_target = pd.DataFrame({
    "ProbenNrPseud": sorted(food_sample_ids)
})

sample_target["Target_Adverse"] = (
    sample_target["ProbenNrPseud"]
    .isin(food_adverse_samples)
    .astype(int)
)

print("Shape:", sample_target.shape)

print("\nTarget distribution:")
print(sample_target["Target_Adverse"].value_counts())

print("\nTarget distribution (%):")
print(
    sample_target["Target_Adverse"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

sample_target.head()

Shape: (8582, 2)

Target distribution:
Target_Adverse
0    8511
1      71
Name: count, dtype: int64

Target distribution (%):
Target_Adverse
0    99.17
1     0.83
Name: proportion, dtype: float64


,ProbenNrPseud,Target_Adverse
0,2,0
1,3,0
2,4,0
3,5,1
4,6,0


# Preliminary Sample-Level Target Dataset

A preliminary binary target dataset was created at the food-sample level.

The resulting dataframe contains **8,582 rows and 2 columns**, where each row represents one unique food sample.

The variables are:

- "ProbenNrPseud" (Pseudonymised Sample Number): unique identifier for the food sample.
- "Target_Adverse" (Adverse Target): preliminary binary classification target.

The target is currently defined as:

- **0 = No clearly adverse assessment identified**
- **1 = At least one clearly adverse assessment identified**

## Target Distribution

| Target | Number of Samples | Percentage |
|---:|---:|---:|
| 0 | 8,511 | 99.17% |
| 1 | 71 | 0.83% |

The resulting classification problem is therefore **highly imbalanced**.

This target remains preliminary until the final assessment definition and predictor variables have been validated.

## Modelling Implication

The identifier "ProbenNrPseud" (Pseudonymised Sample Number) will not be used as a predictive feature.

It will instead be retained for sample identification, grouping, train-test separation where appropriate, and traceability.

The next stage is to determine which variables can safely be represented at the sample level without introducing information from the assessment outcome itself.

In [30]:
# Inspect consistency of important candidate predictors
# within each ProbenNrPseud (Pseudonymised Sample Number)

candidate_columns = [
    "ProbenNrPseud",
    "PnMgT",
    "MatrixGrT",
    "MatrixT",
    "BetriebsartT",
    "PNDat",
    "HerkStaatT",
    "VerarbeitungT",
    "VerpackungT"
]

sample_features_raw = []

for chunk in pd.read_csv(
    file_path,
    sep=";",
    encoding="latin1",
    usecols=candidate_columns,
    chunksize=100_000,
    low_memory=False
):
    # Keep only food-scope samples
    chunk = chunk[
        chunk["ProbenNrPseud"].isin(food_sample_ids)
    ]

    sample_features_raw.append(
        chunk.drop_duplicates()
    )

sample_features_raw = (
    pd.concat(sample_features_raw, ignore_index=True)
    .drop_duplicates()
)

# Check how many unique values each variable has within each sample
consistency_summary = {}

for column in candidate_columns[1:]:
    unique_per_sample = (
        sample_features_raw
        .groupby("ProbenNrPseud")[column]
        .nunique(dropna=True)
    )

    consistency_summary[column] = {
        "Samples_with_1_value": (unique_per_sample == 1).sum(),
        "Samples_with_multiple_values": (unique_per_sample > 1).sum(),
        "Samples_with_no_value": (unique_per_sample == 0).sum()
    }

consistency_summary = pd.DataFrame(consistency_summary).T

consistency_summary

,Samples_with_1_value,Samples_with_multiple_values,Samples_with_no_value
PnMgT,8582,0,0
MatrixGrT,8582,0,0
MatrixT,8582,0,0
BetriebsartT,8582,0,0
PNDat,8582,0,0
HerkStaatT,8580,2,0
VerarbeitungT,8409,95,78
VerpackungT,8550,0,32


# Consistency of Candidate Sample-Level Predictors

Candidate predictor variables were examined to determine whether they contain a consistent value within each "ProbenNrPseud" (Pseudonymised Sample Number).

This step is necessary because the original dataset contains multiple analytical records for each sample, while the planned prediction target is defined at the sample level.

## Results

| Variable | Samples With One Value | Samples With Multiple Values | Samples With No Value |
|---|---:|---:|---:|
| "PnMgT" (Sampling Programme Description) | 8,582 | 0 | 0 |
| "MatrixGrT" (Matrix Group Description) | 8,582 | 0 | 0 |
| "MatrixT" (Matrix Description) | 8,582 | 0 | 0 |
| "BetriebsartT" (Business Type Description) | 8,582 | 0 | 0 |
| "PNDat" (Sampling Date) | 8,582 | 0 | 0 |
| "HerkStaatT" (Country of Origin Description) | 8,580 | 2 | 0 |
| "VerarbeitungT" (Processing Description) | 8,409 | 95 | 78 |
| "VerpackungT" (Packaging Description) | 8,550 | 0 | 32 |

## Interpretation

Several important candidate predictors show complete sample-level consistency.

"PnMgT" (Sampling Programme Description), "MatrixGrT" (Matrix Group Description), "MatrixT" (Matrix Description), "BetriebsartT" (Business Type Description), and "PNDat" (Sampling Date) each have exactly one observed value for every one of the **8,582 food samples**.

These variables can therefore be represented naturally in a one-row-per-sample modelling dataset.

"HerkStaatT" (Country of Origin Description) is also highly consistent, with only **2 samples** containing multiple observed values.

"VerpackungT" (Packaging Description) has no conflicting values within samples, although **32 samples** have no observed value.

"VerarbeitungT" (Processing Description) requires greater attention because **95 samples** contain multiple values and **78 samples** contain no observed value.

## Feature-Engineering Implication

Variables with one consistent value per sample can be transferred directly to the sample-level feature dataset.

Variables containing multiple values should not be reduced automatically by simply selecting the first observed value. Their structure should first be understood and an appropriate aggregation or encoding strategy selected.

Missing values will also be handled explicitly during preprocessing rather than being silently discarded.

## Leakage Consideration

These candidate variables describe characteristics such as the product, sampling programme, business type, origin, processing, packaging, and sampling date.

They are being investigated as potential predictors because they can potentially describe a sample independently of the final adverse assessment.

Assessment and outcome variables such as "Bewertung" (Assessment), "BewertungT" (Assessment Description), and variables that directly reveal the analytical outcome will not be included as predictors of the target.

In [31]:
# Count unique values for candidate sample-level predictors

predictor_cardinality = (
    sample_features_raw[
        [
            "PnMgT",
            "MatrixGrT",
            "MatrixT",
            "BetriebsartT",
            "HerkStaatT",
            "VerarbeitungT",
            "VerpackungT"
        ]
    ]
    .nunique(dropna=True)
    .sort_values()
    .to_frame(name="Unique_Values")
)

predictor_cardinality

,Unique_Values
PnMgT,3
MatrixGrT,19
VerpackungT,31
VerarbeitungT,33
HerkStaatT,87
MatrixT,120
BetriebsartT,144


# Cardinality of Candidate Predictors

The number of unique categories in the candidate sample-level predictor variables was examined before feature encoding.

## Results

| Variable | Unique Values |
|---|---:|
| "PnMgT" (Sampling Programme Description) | 3 |
| "MatrixGrT" (Matrix Group Description) | 19 |
| "VerpackungT" (Packaging Description) | 31 |
| "VerarbeitungT" (Processing Description) | 33 |
| "HerkStaatT" (Country of Origin Description) | 87 |
| "MatrixT" (Matrix Description) | 120 |
| "BetriebsartT" (Business Type Description) | 144 |

## Interpretation

The candidate predictors contain different levels of categorical complexity.

"PnMgT" (Sampling Programme Description) has very low cardinality with only **3 categories**, while "MatrixGrT" (Matrix Group Description) contains **19 categories**.

"HerkStaatT" (Country of Origin Description), "MatrixT" (Matrix Description), and "BetriebsartT" (Business Type Description) have higher cardinality, with **87, 120, and 144 categories**, respectively.

None of the currently selected sample-level predictors contains thousands of categories, making their use in the predictive analysis technically feasible.

However, higher-cardinality categorical variables require careful preprocessing because one-hot encoding can substantially increase the number of model features.

## Modelling Implication

The appropriate encoding strategy will be selected during preprocessing and evaluated together with the chosen machine-learning algorithms.

For interpretable models such as Logistic Regression, categorical encoding will be required.

Tree-based models such as Decision Tree, Random Forest, and XGBoost (Extreme Gradient Boosting) will also require an appropriate representation of these categorical predictors.

Encoding will be fitted using the training data only to prevent information leakage.

No encoding is performed at this stage.

In [32]:
# Distribution of Country of Origin Description
# at the sample level

origin_distribution = (
    sample_features_raw[
        ["ProbenNrPseud", "HerkStaatT"]
    ]
    .drop_duplicates()
    ["HerkStaatT"]
    .value_counts()
    .to_frame(name="Sample_Count")
)

origin_distribution["Percentage"] = (
    origin_distribution["Sample_Count"]
    / len(food_sample_ids)
    * 100
).round(2)

origin_distribution.head(20)

,Sample_Count,Percentage
HerkStaatT,,
Deutschland,3357,39.12
Ungeklärt,813,9.47
Spanien,725,8.45
Ohne Angabe,641,7.47
Italien,506,5.90
Niederlande,283,3.30
"Frankreich, einschl. Korsika",168,1.96
Türkei,139,1.62
Tunesien,133,1.55


# Distribution of Country of Origin

The sample-level distribution of "HerkStaatT" (Country of Origin Description) was examined for the food-scope population.

There are **87 unique origin categories**.

## Most Common Origins

| Country of Origin | Samples | Percentage |
|---|---:|---:|
| "Deutschland" (Germany) | 3,357 | 39.12% |
| "Ungeklärt" (Unresolved/Unknown) | 813 | 9.47% |
| "Spanien" (Spain) | 725 | 8.45% |
| "Ohne Angabe" (No information provided) | 641 | 7.47% |
| "Italien" (Italy) | 506 | 5.90% |
| "Niederlande" (Netherlands) | 283 | 3.30% |
| "Frankreich, einschl. Korsika" (France, including Corsica) | 168 | 1.96% |
| "Türkei" (Türkiye) | 139 | 1.62% |
| "Tunesien" (Tunisia) | 133 | 1.55% |
| "Belgien" (Belgium) | 122 | 1.42% |
| "Vietnam" (Vietnam) | 115 | 1.34% |
| "Ägypten" (Egypt) | 113 | 1.32% |
| "Indien, einschl. Sikkim und Goa" (India, including Sikkim and Goa) | 112 | 1.31% |

## Interpretation

"Deutschland" (Germany) is the dominant recorded country of origin, accounting for approximately **39.12%** of the food samples.

The dataset nevertheless contains substantial international representation, indicating that the BVL monitoring programme covers products originating from many countries.

Two categories represent unavailable or uncertain origin information:

- "Ungeklärt" (Unresolved/Unknown): **9.47%**
- "Ohne Angabe" (No information provided): **7.47%**

Together, these categories account for approximately **16.94%** of the food samples.

These values represent meaningful information about the availability of origin data and should not automatically be treated as ordinary missing values or removed.

## Feature-Engineering Implication

With **87 unique origin categories**, "HerkStaatT" (Country of Origin Description) is a moderately high-cardinality categorical predictor.

Rare countries may later require careful treatment during preprocessing to avoid creating many sparsely populated encoded features.

Any grouping strategy will be performed only after examining the relationship between country of origin and the preliminary adverse target.

No origin categories are grouped or removed at this stage.

In [33]:
# Compare Country of Origin Description with the preliminary adverse target

origin_target = (
    sample_features_raw[
        ["ProbenNrPseud", "HerkStaatT"]
    ]
    .drop_duplicates()
)

origin_target["Target_Adverse"] = (
    origin_target["ProbenNrPseud"]
    .isin(food_adverse_samples)
    .astype(int)
)

origin_risk = (
    origin_target
    .groupby("HerkStaatT")
    .agg(
        Total_Samples=("ProbenNrPseud", "nunique"),
        Adverse_Samples=("Target_Adverse", "sum")
    )
)

origin_risk["Adverse_Rate_Percent"] = (
    origin_risk["Adverse_Samples"]
    / origin_risk["Total_Samples"]
    * 100
).round(2)

# Only show origins with at least 30 samples
origin_risk_reliable = (
    origin_risk[
        origin_risk["Total_Samples"] >= 30
    ]
    .sort_values(
        "Adverse_Rate_Percent",
        ascending=False
    )
)

origin_risk_reliable.head(20)

,Total_Samples,Adverse_Samples,Adverse_Rate_Percent
HerkStaatT,,,
Vereinigte Staaten von Amerika,63,4,6.35
"China, einschl. Tibet",63,2,3.17
Türkei,139,4,2.88
Argentinien,43,1,2.33
"Frankreich, einschl. Korsika",168,3,1.79
"Korea, Republik",73,1,1.37
Griechenland,75,1,1.33
Ohne Angabe,641,7,1.09
Ungeklärt,813,8,0.98


# Country of Origin and Observed Adverse Rate

The relationship between "HerkStaatT" (Country of Origin Description) and the preliminary adverse target was examined at the sample level.

To reduce misleading rankings caused by extremely small sample sizes, the descriptive comparison shown here was restricted to origin categories containing at least **30 samples**.

This threshold is used only for descriptive interpretation and does not remove these observations from the modelling dataset.

## Highest Observed Adverse Rates

| Country of Origin | Total Samples | Adverse Samples | Observed Adverse Rate |
|---|---:|---:|---:|
| "Vereinigte Staaten von Amerika" (United States of America) | 63 | 4 | 6.35% |
| "China, einschl. Tibet" (China, including Tibet) | 63 | 2 | 3.17% |
| "Türkei" (Türkiye) | 139 | 4 | 2.88% |
| "Argentinien" (Argentina) | 43 | 1 | 2.33% |
| "Frankreich, einschl. Korsika" (France, including Corsica) | 168 | 3 | 1.79% |
| "Korea, Republik" (Republic of Korea) | 73 | 1 | 1.37% |
| "Griechenland" (Greece) | 75 | 1 | 1.33% |
| "Ohne Angabe" (No information provided) | 641 | 7 | 1.09% |
| "Ungeklärt" (Unresolved/Unknown) | 813 | 8 | 0.98% |
| "Ägypten" (Egypt) | 113 | 1 | 0.88% |
| "Vietnam" (Vietnam) | 115 | 1 | 0.87% |
| "Deutschland" (Germany) | 3,357 | 28 | 0.83% |

## Interpretation

The observed adverse rate varies across recorded countries of origin.

"Vereinigte Staaten von Amerika" (United States of America) has the highest observed rate among origins with at least 30 samples, at **6.35%**. However, this corresponds to only **4 adverse samples among 63 samples**.

"Deutschland" (Germany), by comparison, contains **28 adverse samples**, the largest absolute number in the displayed groups, but its much larger denominator of **3,357 samples** produces an observed adverse rate of approximately **0.83%**.

This demonstrates the importance of distinguishing between the **number of adverse samples** and the **proportion of samples that are adverse**.

## Statistical Caution

These results are descriptive associations and should not be interpreted as evidence that a particular country of origin causes food-safety non-compliance.

Differences may also be influenced by:

- product composition;
- monitoring and sampling strategy;
- analytical parameters tested;
- business type;
- sample size;
- other characteristics of the monitoring programme.

Some origin groups contain relatively few observations and adverse cases. Their estimated adverse rates may therefore be unstable.

The relationship between origin and adverse outcome should later be evaluated together with other predictors and, where appropriate, inferential statistical methods.

## Modelling Implication

"HerkStaatT" (Country of Origin Description) appears potentially informative and will remain a candidate predictor.

However, rare origin categories may later require grouping or another suitable encoding strategy. Such preprocessing decisions will be made using the training data to minimise information leakage.

In [34]:
# Create contingency table:
# Country of Origin Description vs Adverse Target

origin_contingency = pd.crosstab(
    origin_target["HerkStaatT"],
    origin_target["Target_Adverse"]
)

from scipy.stats import chi2_contingency

chi2, p_value, dof, expected = chi2_contingency(
    origin_contingency
)

expected_df = pd.DataFrame(
    expected,
    index=origin_contingency.index,
    columns=origin_contingency.columns
)

cells_below_5 = (expected_df < 5).sum().sum()
total_cells = expected_df.size

print(f"Chi-square statistic: {chi2:.2f}")
print(f"P-value: {p_value:.6f}")
print(f"Degrees of freedom: {dof}")
print(f"Cells with expected frequency < 5: {cells_below_5}")
print(f"Total contingency-table cells: {total_cells}")
print(
    f"Percentage of cells below 5: "
    f"{cells_below_5 / total_cells * 100:.2f}%"
)

Chi-square statistic: 103.74
P-value: 0.093483
Degrees of freedom: 86
Cells with expected frequency < 5: 114
Total contingency-table cells: 174
Percentage of cells below 5: 65.52%


# Chi-Square Assumption Check for Country of Origin

A chi-square test of independence was initially considered to evaluate whether "HerkStaatT" (Country of Origin Description) is associated with the preliminary adverse target.

The hypotheses were:

**Null hypothesis (H₀):**  
Country of origin and adverse outcome are independent.

**Alternative hypothesis (H₁):**  
Country of origin and adverse outcome are associated.

## Initial Test Result

- Chi-square statistic: **103.74**
- p-value: **0.093483**
- Degrees of freedom: **86**

However, the assumptions of the chi-square approximation were also examined.

Of the **174 expected contingency-table cells**, **114 cells (65.52%)** had an expected frequency below 5.

## Interpretation

The contingency table is highly sparse because there are **87 origin categories** but only **71 adverse food samples**.

A large proportion of expected cell frequencies therefore falls below the level normally considered suitable for a standard chi-square approximation.

Consequently, the p-value of **0.093483 should not be treated as a reliable inferential conclusion** for the original 87-category country variable.

The test result is retained for transparency, but no statistical conclusion about independence or association will be drawn from this version of the chi-square test.

## Next Statistical Approach

A more defensible analysis requires reducing sparse origin categories into meaningful broader groups before repeating the association test.

This grouping should be determined from interpretable characteristics rather than from adverse outcomes themselves, in order to avoid target leakage or outcome-driven category construction.

In [35]:
# Examine rarity of Country of Origin categories

origin_counts = (
    sample_features_raw[
        ["ProbenNrPseud", "HerkStaatT"]
    ]
    .drop_duplicates()
    ["HerkStaatT"]
    .value_counts()
)

rarity_summary = pd.DataFrame({
    "Threshold": [
        "< 5 samples",
        "< 10 samples",
        "< 20 samples",
        "< 30 samples",
        "< 50 samples"
    ],
    "Number_of_Categories": [
        (origin_counts < 5).sum(),
        (origin_counts < 10).sum(),
        (origin_counts < 20).sum(),
        (origin_counts < 30).sum(),
        (origin_counts < 50).sum()
    ]
})

rarity_summary

,Threshold,Number_of_Categories
0,< 5 samples,26
1,< 10 samples,41
2,< 20 samples,52
3,< 30 samples,56
4,< 50 samples,62


# Sparsity of Country-of-Origin Categories

The frequency distribution of "HerkStaatT" (Country of Origin Description) was examined to determine how many origin categories contain relatively small numbers of samples.

## Results

| Frequency Threshold | Number of Origin Categories |
|---|---:|
| Fewer than 5 samples | 26 |
| Fewer than 10 samples | 41 |
| Fewer than 20 samples | 52 |
| Fewer than 30 samples | 56 |
| Fewer than 50 samples | 62 |

## Interpretation

The country-of-origin variable contains substantial category sparsity.

Of the **87 unique origin categories**:

- **26 categories** contain fewer than 5 samples.
- **41 categories** contain fewer than 10 samples.
- **56 categories** contain fewer than 30 samples.
- **62 categories** contain fewer than 50 samples.

This means that only **25 of the 87 origin categories** contain at least 30 samples.

The high number of rare categories helps explain why the original chi-square contingency table contained a large proportion of expected frequencies below 5.

## Statistical and Modelling Implication

Using all 87 origin categories individually may create statistical instability and a large number of sparsely populated encoded features.

A sensible later preprocessing strategy may therefore combine rare origin categories into a broader "Other" category or construct meaningful geographical groupings.

Importantly, any grouping strategy should be based on the predictor distribution or an external geographical definition rather than on which countries happened to have adverse outcomes. This avoids using target information to construct the predictor.

The original "HerkStaatT" (Country of Origin Description) values will remain unchanged in the raw dataset.

In [36]:
# Compare possible rare-category thresholds
# for Country of Origin Description

threshold_results = []

for threshold in [5, 10, 20, 30, 50]:
    
    rare_origins = origin_counts[
        origin_counts < threshold
    ]
    
    threshold_results.append({
        "Minimum_Samples_Per_Category": threshold,
        "Rare_Categories_Grouped": len(rare_origins),
        "Samples_Moved_to_Other": rare_origins.sum(),
        "Percentage_of_Samples": round(
            rare_origins.sum() / len(food_sample_ids) * 100,
            2
        ),
        "Categories_After_Grouping": (
            (origin_counts >= threshold).sum() + 1
        )
    })

threshold_comparison = pd.DataFrame(threshold_results)

threshold_comparison

,Minimum_Samples_Per_Category,Rare_Categories_Grouped,Samples_Moved_to_Other,Percentage_of_Samples,Categories_After_Grouping
0,5,26,62,0.72,62
1,10,41,153,1.78,47
2,20,52,289,3.37,36
3,30,56,398,4.64,32
4,50,62,611,7.12,26


# Selection of a Provisional Rare-Category Threshold

Several minimum-frequency thresholds were compared for grouping rare values of "HerkStaatT" (Country of Origin Description).

## Threshold Comparison

| Minimum Samples per Category | Rare Categories Grouped | Samples Moved to "Other" | Percentage of Samples | Categories After Grouping |
|---:|---:|---:|---:|---:|
| 5 | 26 | 62 | 0.72% | 62 |
| 10 | 41 | 153 | 1.78% | 47 |
| 20 | 52 | 289 | 3.37% | 36 |
| 30 | 56 | 398 | 4.64% | 32 |
| 50 | 62 | 611 | 7.12% | 26 |

## Interpretation

A minimum category size of **20 samples** provides a reasonable balance between reducing sparsity and preserving the original information.

Using this threshold:

- **52 rare origin categories** would be grouped.
- Only **289 samples**, representing approximately **3.37%** of the food-scope dataset, would be assigned to a broader "Other" category.
- The number of origin categories would fall from **87 to 36**.

This substantially reduces category sparsity while retaining the original country information for approximately **96.63%** of the samples.

A threshold of 30 or 50 samples would reduce the number of categories further, but would also combine a larger proportion of observations into the "Other" category.

Therefore, **20 samples is selected as a provisional rare-category threshold** for exploratory analysis.

For the final machine-learning pipeline, rare-category grouping will be learned from the training data only so that information from the test dataset is not used during preprocessing.

In [37]:
# Create provisional grouped Country of Origin variable
# using a minimum frequency of 20 samples

rare_origins_20 = set(
    origin_counts[
        origin_counts < 20
    ].index
)

origin_target_grouped = origin_target.copy()

origin_target_grouped["HerkStaatT_Grouped"] = (
    origin_target_grouped["HerkStaatT"]
    .where(
        ~origin_target_grouped["HerkStaatT"].isin(rare_origins_20),
        "Other"
    )
)

# Contingency table
origin_grouped_contingency = pd.crosstab(
    origin_target_grouped["HerkStaatT_Grouped"],
    origin_target_grouped["Target_Adverse"]
)

# Chi-square test
chi2_g, p_value_g, dof_g, expected_g = chi2_contingency(
    origin_grouped_contingency
)

expected_grouped_df = pd.DataFrame(
    expected_g,
    index=origin_grouped_contingency.index,
    columns=origin_grouped_contingency.columns
)

cells_below_5_g = (
    expected_grouped_df < 5
).sum().sum()

total_cells_g = expected_grouped_df.size

print(f"Grouped origin categories: {origin_grouped_contingency.shape[0]}")
print(f"Chi-square statistic: {chi2_g:.2f}")
print(f"P-value: {p_value_g:.6f}")
print(f"Degrees of freedom: {dof_g}")
print(f"Cells with expected frequency < 5: {cells_below_5_g}")
print(f"Total contingency-table cells: {total_cells_g}")
print(
    f"Percentage of cells below 5: "
    f"{cells_below_5_g / total_cells_g * 100:.2f}%"
)

Grouped origin categories: 36
Chi-square statistic: 55.58
P-value: 0.014904
Degrees of freedom: 35
Cells with expected frequency < 5: 32
Total contingency-table cells: 72
Percentage of cells below 5: 44.44%


# Chi-Square Test After Rare-Category Grouping

Rare country-of-origin categories containing fewer than 20 samples were provisionally grouped into an "Other" category.

This reduced the number of "HerkStaatT" (Country of Origin Description) categories from **87 to 36**.

## Grouped Chi-Square Result

- Chi-square statistic: **55.58**
- p-value: **0.014904**
- Degrees of freedom: **35**
- Expected cells below 5: **32 of 72**
- Percentage of expected cells below 5: **44.44%**

## Interpretation

Grouping rare origin categories substantially improved the sparsity of the contingency table.

Before grouping, **65.52%** of expected cell frequencies were below 5.

After grouping, this decreased to **44.44%**.

Although the calculated p-value is below 0.05, the chi-square approximation still has a substantial expected-frequency problem because nearly half of the contingency-table cells remain below 5.

Therefore, the p-value of **0.014904 should not yet be interpreted as reliable evidence of a statistically significant association** between country of origin and the adverse target.

The grouped result is retained as exploratory evidence only.

## Statistical Conclusion

The descriptive analysis suggests that observed adverse rates differ across countries of origin, but the extreme rarity of the adverse class makes conventional chi-square inference difficult.

Country of origin remains a potentially useful predictive feature, but stronger evidence should come from the multivariable machine-learning analysis and from statistical procedures suitable for sparse contingency tables.

In [38]:
# Inspect adverse counts after grouping

grouped_origin_summary = (
    origin_target_grouped
    .groupby("HerkStaatT_Grouped")
    .agg(
        Total_Samples=("ProbenNrPseud", "nunique"),
        Adverse_Samples=("Target_Adverse", "sum")
    )
)

grouped_origin_summary["Adverse_Rate_Percent"] = (
    grouped_origin_summary["Adverse_Samples"]
    / grouped_origin_summary["Total_Samples"]
    * 100
).round(2)

grouped_origin_summary = (
    grouped_origin_summary
    .sort_values(
        ["Adverse_Samples", "Adverse_Rate_Percent"],
        ascending=False
    )
)

grouped_origin_summary.head(20)

,Total_Samples,Adverse_Samples,Adverse_Rate_Percent
HerkStaatT_Grouped,,,
Deutschland,3357,28,0.83
Ungeklärt,813,8,0.98
Ohne Angabe,641,7,1.09
Vereinigte Staaten von Amerika,63,4,6.35
Türkei,139,4,2.88
"Frankreich, einschl. Korsika",168,3,1.79
Other,289,3,1.04
Italien,506,3,0.59
"China, einschl. Tibet",63,2,3.17


# Adverse Cases Within the Grouped Country-of-Origin Variable

After grouping rare country-of-origin categories, the distribution of adverse cases across the remaining origin groups was examined.

## Key Results

The largest number of adverse cases occurs in:

- "Deutschland" (Germany): **28 adverse samples out of 3,357** → **0.83%**
- "Ungeklärt" (Unresolved/Unknown): **8 out of 813** → **0.98%**
- "Ohne Angabe" (No information provided): **7 out of 641** → **1.09%**
- "Vereinigte Staaten von Amerika" (United States of America): **4 out of 63** → **6.35%**
- "Türkei" (Türkiye): **4 out of 139** → **2.88%**
- "Frankreich, einschl. Korsika" (France, including Corsica): **3 out of 168** → **1.79%**
- "Other" (Other): **3 out of 289** → **1.04%**
- "Italien" (Italy): **3 out of 506** → **0.59%**

Many other origin categories contain only **one adverse case** or none at all.

## Interpretation

This result explains why the chi-square assumptions remain weak even after rare-category grouping.

The main limitation is not only the number of country categories. The more important issue is the extremely small size of the adverse class, with only **71 adverse food samples in total**.

Because the adverse cases are distributed across many origin categories, most cells in the contingency table still contain very few positive observations.

This produces unstable category-specific adverse rates and low expected frequencies.

For example:

- "Vereinigte Staaten von Amerika" (United States of America) has an observed adverse rate of **6.35%**, but this is based on only **4 adverse samples**.
- "China, einschl. Tibet" (China, including Tibet) has an observed adverse rate of **3.17%**, based on only **2 adverse samples**.
- "Tschechische Republik" (Czech Republic) has an observed adverse rate of **3.85%**, based on only **1 adverse sample**.

These rates should therefore be interpreted cautiously.

## Statistical Conclusion

Country of origin shows potentially interesting differences in observed adverse rates, but the very small number of adverse cases limits the reliability of conventional category-by-category statistical inference.

For this project, "HerkStaatT" (Country of Origin Description) is better treated as:

- an exploratory descriptive variable; and
- a candidate predictor within the multivariable machine-learning models.

The predictive models can evaluate whether country of origin contributes useful information when considered together with other sample characteristics.

In [39]:
# Compare Business Type Description with the preliminary adverse target

business_target = (
    sample_features_raw[
        ["ProbenNrPseud", "BetriebsartT"]
    ]
    .drop_duplicates()
)

business_target["Target_Adverse"] = (
    business_target["ProbenNrPseud"]
    .isin(food_adverse_samples)
    .astype(int)
)

business_risk = (
    business_target
    .groupby("BetriebsartT")
    .agg(
        Total_Samples=("ProbenNrPseud", "nunique"),
        Adverse_Samples=("Target_Adverse", "sum")
    )
)

business_risk["Adverse_Rate_Percent"] = (
    business_risk["Adverse_Samples"]
    / business_risk["Total_Samples"]
    * 100
).round(2)

business_risk_reliable = (
    business_risk[
        business_risk["Total_Samples"] >= 30
    ]
    .sort_values(
        ["Adverse_Rate_Percent", "Adverse_Samples"],
        ascending=False
    )
)

business_risk_reliable.head(20)

,Total_Samples,Adverse_Samples,Adverse_Rate_Percent
BetriebsartT,,,
Direktvermarkter/Verkaufsstelle Obst und Gemüse,55,4,7.27
Erzeuger von Lebensmitteln pflanzlicher Herkunft,39,2,5.13
Mühlenbetrieb,104,2,1.92
Bäckerei,68,1,1.47
Lebensmittellager Zentrallager,423,5,1.18
Großhändler für Lebensmitteleinzelhandel (Vollsortiment),92,1,1.09
Einzelhändler,233,2,0.86
Lebensmittelgeschäft und (eigenständige) -verkaufsabteilung (incl. Supermarkt),5380,43,0.80
Großhändler von Obst und Gemüse und -erzeugnissen,345,1,0.29


# Business Type and Observed Adverse Rate

The relationship between "BetriebsartT" (Business Type Description) and the preliminary adverse target was examined at the food-sample level.

For descriptive comparison, only business-type categories containing at least **30 samples** were included in the displayed ranking. This threshold is used only for interpretation and does not remove observations from the modelling dataset.

## Selected Results

| Business Type | Total Samples | Adverse Samples | Observed Adverse Rate |
|---|---:|---:|---:|
| "Direktvermarkter/Verkaufsstelle Obst und Gemüse" (Direct marketer/sales outlet for fruit and vegetables) | 55 | 4 | 7.27% |
| "Erzeuger von Lebensmitteln pflanzlicher Herkunft" (Producer of foods of plant origin) | 39 | 2 | 5.13% |
| "Mühlenbetrieb" (Milling operation) | 104 | 2 | 1.92% |
| "Bäckerei" (Bakery) | 68 | 1 | 1.47% |
| "Lebensmittellager Zentrallager" (Food warehouse/central warehouse) | 423 | 5 | 1.18% |
| "Großhändler für Lebensmitteleinzelhandel (Vollsortiment)" (Wholesaler supplying full-range food retailers) | 92 | 1 | 1.09% |
| "Einzelhändler" (Retailer) | 233 | 2 | 0.86% |
| "Lebensmittelgeschäft und (eigenständige) -verkaufsabteilung (incl. Supermarkt)" (Food store and independent food sales department, including supermarket) | 5,380 | 43 | 0.80% |
| "Großhändler von Obst und Gemüse und -erzeugnissen" (Wholesaler of fruit, vegetables and related products) | 345 | 1 | 0.29% |

## Interpretation

The observed adverse rate differs considerably between some business-type categories.

"Direktvermarkter/Verkaufsstelle Obst und Gemüse" (Direct marketer/sales outlet for fruit and vegetables) has the highest observed rate among the displayed categories at **7.27%**, corresponding to 4 adverse samples among 55 samples.

"Erzeuger von Lebensmitteln pflanzlicher Herkunft" (Producer of foods of plant origin) has an observed adverse rate of **5.13%**, although this is based on only 2 adverse samples among 39 samples.

In contrast, "Lebensmittelgeschäft und (eigenständige) -verkaufsabteilung (incl. Supermarkt)" (Food store and independent food sales department, including supermarket) contains **43 adverse samples**, the largest absolute number, but also contains 5,380 samples overall. Its observed adverse rate is therefore approximately **0.80%**.

This again demonstrates the importance of distinguishing between absolute adverse counts and adverse rates.

## Statistical Caution

The higher rates observed for some business types should not be interpreted as evidence that the business type itself causes non-compliance.

Product group, country of origin, sampling strategy, analytical parameters and other characteristics may differ systematically between business types.

Furthermore, several of the highest observed rates are based on relatively small numbers of adverse cases.

## Modelling Implication

"BetriebsartT" (Business Type Description) remains a potentially informative candidate predictor.

However, with **144 original categories**, it is a high-cardinality categorical variable. Rare categories will require appropriate handling during preprocessing, with any grouping or encoding strategy learned from the training data only.

In [40]:
# Examine rarity of Business Type Description categories

business_counts = (
    sample_features_raw[
        ["ProbenNrPseud", "BetriebsartT"]
    ]
    .drop_duplicates()
    ["BetriebsartT"]
    .value_counts()
)

business_rarity_summary = pd.DataFrame({
    "Threshold": [
        "< 5 samples",
        "< 10 samples",
        "< 20 samples",
        "< 30 samples",
        "< 50 samples"
    ],
    "Number_of_Categories": [
        (business_counts < 5).sum(),
        (business_counts < 10).sum(),
        (business_counts < 20).sum(),
        (business_counts < 30).sum(),
        (business_counts < 50).sum()
    ]
})

business_rarity_summary

,Threshold,Number_of_Categories
0,< 5 samples,76
1,< 10 samples,96
2,< 20 samples,112
3,< 30 samples,117
4,< 50 samples,128


# Sparsity of Business-Type Categories

The frequency distribution of "BetriebsartT" (Business Type Description) was examined because the variable contains **144 unique categories**.

## Results

| Frequency Threshold | Number of Business-Type Categories |
|---|---:|
| Fewer than 5 samples | 76 |
| Fewer than 10 samples | 96 |
| Fewer than 20 samples | 112 |
| Fewer than 30 samples | 117 |
| Fewer than 50 samples | 128 |

## Interpretation

"BetriebsartT" (Business Type Description) is a highly sparse categorical variable.

Of its **144 categories**:

- **76 categories** contain fewer than 5 samples.
- **96 categories** contain fewer than 10 samples.
- **112 categories** contain fewer than 20 samples.
- **117 categories** contain fewer than 30 samples.
- **128 categories** contain fewer than 50 samples.

Therefore, only **32 business-type categories** contain at least 20 samples.

This sparsity is more pronounced than that observed for "HerkStaatT" (Country of Origin Description).

## Modelling Implication

Directly one-hot encoding all 144 business-type categories could create many features supported by very few observations.

Rare-category grouping is therefore likely to be useful during preprocessing.

However, the original business-type information will be preserved in the raw data, and the final grouping transformation will be learned from the training data only to avoid information leakage.

In [41]:
# Compare possible rare-category thresholds
# for Business Type Description

business_threshold_results = []

for threshold in [5, 10, 20, 30, 50]:

    rare_businesses = business_counts[
        business_counts < threshold
    ]

    business_threshold_results.append({
        "Minimum_Samples_Per_Category": threshold,
        "Rare_Categories_Grouped": len(rare_businesses),
        "Samples_Moved_to_Other": rare_businesses.sum(),
        "Percentage_of_Samples": round(
            rare_businesses.sum() / len(food_sample_ids) * 100,
            2
        ),
        "Categories_After_Grouping": (
            (business_counts >= threshold).sum() + 1
        )
    })

business_threshold_comparison = pd.DataFrame(
    business_threshold_results
)

business_threshold_comparison

,Minimum_Samples_Per_Category,Rare_Categories_Grouped,Samples_Moved_to_Other,Percentage_of_Samples,Categories_After_Grouping
0,5,76,143,1.67,69
1,10,96,275,3.20,49
2,20,112,505,5.88,33
3,30,117,628,7.32,28
4,50,128,1042,12.14,17


# Selection of a Provisional Rare-Category Threshold for Business Type

Several minimum-frequency thresholds were compared for grouping rare values of "BetriebsartT" (Business Type Description).

## Threshold Comparison

| Minimum Samples per Category | Rare Categories Grouped | Samples Moved to "Other" | Percentage of Samples | Categories After Grouping |
|---:|---:|---:|---:|---:|
| 5 | 76 | 143 | 1.67% | 69 |
| 10 | 96 | 275 | 3.20% | 49 |
| 20 | 112 | 505 | 5.88% | 33 |
| 30 | 117 | 628 | 7.32% | 28 |
| 50 | 128 | 1,042 | 12.14% | 17 |

## Interpretation

A minimum category size of **20 samples** provides a reasonable compromise between reducing sparsity and preserving detailed business-type information.

Using this threshold:

- **112 rare business-type categories** would be grouped.
- **505 samples**, representing approximately **5.88%** of the food-scope dataset, would be assigned to "Other".
- The number of categories would decrease from **144 to 33**.

This produces a much more manageable categorical variable while preserving the original category for approximately **94.12%** of the samples.

More aggressive thresholds such as 30 or 50 would reduce the number of categories further but would also combine a substantially larger share of observations.

Therefore, **20 samples is selected as a provisional rare-category threshold** for exploratory analysis of "BetriebsartT" (Business Type Description).

For the final machine-learning pipeline, the grouping rule will be fitted on the training data only.

In [42]:
# Create provisional grouped Business Type variable
# using a minimum frequency of 20 samples

rare_businesses_20 = set(
    business_counts[
        business_counts < 20
    ].index
)

business_target_grouped = business_target.copy()

business_target_grouped["BetriebsartT_Grouped"] = (
    business_target_grouped["BetriebsartT"]
    .where(
        ~business_target_grouped["BetriebsartT"].isin(rare_businesses_20),
        "Other"
    )
)

# Contingency table
business_grouped_contingency = pd.crosstab(
    business_target_grouped["BetriebsartT_Grouped"],
    business_target_grouped["Target_Adverse"]
)

# Chi-square test
chi2_b, p_value_b, dof_b, expected_b = chi2_contingency(
    business_grouped_contingency
)

expected_business_df = pd.DataFrame(
    expected_b,
    index=business_grouped_contingency.index,
    columns=business_grouped_contingency.columns
)

cells_below_5_b = (
    expected_business_df < 5
).sum().sum()

total_cells_b = expected_business_df.size

print(f"Grouped business categories: {business_grouped_contingency.shape[0]}")
print(f"Chi-square statistic: {chi2_b:.2f}")
print(f"P-value: {p_value_b:.6f}")
print(f"Degrees of freedom: {dof_b}")
print(f"Cells with expected frequency < 5: {cells_below_5_b}")
print(f"Total contingency-table cells: {total_cells_b}")
print(
    f"Percentage of cells below 5: "
    f"{cells_below_5_b / total_cells_b * 100:.2f}%"
)

Grouped business categories: 33
Chi-square statistic: 60.04
P-value: 0.001925
Degrees of freedom: 32
Cells with expected frequency < 5: 32
Total contingency-table cells: 66
Percentage of cells below 5: 48.48%


# Chi-Square Test After Grouping Rare Business Types

Rare values of "BetriebsartT" (Business Type Description) containing fewer than 20 samples were provisionally grouped into an "Other" category.

This reduced the number of business-type categories from **144 to 33**.

## Grouped Chi-Square Result

- Chi-square statistic: **60.04**
- p-value: **0.001925**
- Degrees of freedom: **32**
- Expected cells below 5: **32 of 66**
- Percentage of expected cells below 5: **48.48%**

## Interpretation

The grouped analysis produces a very small p-value, which might initially suggest an association between business type and the adverse target.

However, the chi-square assumptions remain weak because **48.48% of the expected contingency-table cells have expected frequencies below 5**.

This is substantially above the level normally considered acceptable for a reliable chi-square approximation.

Therefore, the p-value of **0.001925 should not be interpreted as definitive evidence of a statistically significant association**.

The result is retained as exploratory evidence only.

## Comparison With Country of Origin

The same limitation was observed for "HerkStaatT" (Country of Origin Description).

The fundamental issue is the very small adverse class of only **71 food samples**, which produces sparse positive counts across many categorical groups even after rare categories are combined.

## Conclusion

"BetriebsartT" (Business Type Description) remains a potentially useful explanatory and predictive variable.

Its usefulness will be evaluated primarily through:

- descriptive adverse-rate comparisons;
- multivariable machine-learning models;
- feature importance or model interpretation methods.

The standard chi-square result will not be used as standalone evidence of association because its expected-frequency assumptions are not sufficiently satisfied.

In [43]:
# Compare Matrix Group Description with the preliminary adverse target

matrix_group_target = (
    sample_features_raw[
        ["ProbenNrPseud", "MatrixGrT"]
    ]
    .drop_duplicates()
)

matrix_group_target["Target_Adverse"] = (
    matrix_group_target["ProbenNrPseud"]
    .isin(food_adverse_samples)
    .astype(int)
)

matrix_group_risk = (
    matrix_group_target
    .groupby("MatrixGrT")
    .agg(
        Total_Samples=("ProbenNrPseud", "nunique"),
        Adverse_Samples=("Target_Adverse", "sum")
    )
)

matrix_group_risk["Adverse_Rate_Percent"] = (
    matrix_group_risk["Adverse_Samples"]
    / matrix_group_risk["Total_Samples"]
    * 100
).round(2)

matrix_group_risk = (
    matrix_group_risk
    .sort_values(
        ["Adverse_Rate_Percent", "Adverse_Samples"],
        ascending=False
    )
)

matrix_group_risk

,Total_Samples,Adverse_Samples,Adverse_Rate_Percent
MatrixGrT,,,
Gewürze,381,14,3.67
Hülsenfrüchte Ölsamen Schalenobst,922,15,1.63
Fleisch warmblütiger Tiere auch tiefgefroren,628,9,1.43
Frischobst einschließlich Rhabarber,1521,15,0.99
Obstprodukte ausgenommen 310000 und 410000 einschl. Rhabarber,523,4,0.76
Kartoffeln und stärkereiche Pflanzenteile,267,2,0.75
Gemüseerzeugn. und Gemüsezuber. ausgen. Rhabarber u. 200700 u. 201700,289,2,0.69
Getreideprodukte Backvormischungen Brotteige Massen und Teige für,550,3,0.55
Getreide,456,2,0.44


# Product Group and Observed Adverse Rate

The relationship between "MatrixGrT" (Matrix Group Description) and the preliminary adverse target was examined at the food-sample level.

Unlike some of the higher-cardinality variables, "MatrixGrT" (Matrix Group Description) contains only **19 food-related categories**, making the comparison easier to interpret.

## Observed Adverse Rates

| Product Group | Total Samples | Adverse Samples | Observed Adverse Rate |
|---|---:|---:|---:|
| "Gewürze" (Spices) | 381 | 14 | 3.67% |
| "Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts) | 922 | 15 | 1.63% |
| "Fleisch warmblütiger Tiere auch tiefgefroren" (Meat from warm-blooded animals, including deep-frozen products) | 628 | 9 | 1.43% |
| "Frischobst einschließlich Rhabarber" (Fresh fruit including rhubarb) | 1,521 | 15 | 0.99% |
| "Obstprodukte ausgenommen 310000 und 410000 einschl. Rhabarber" (Fruit products excluding categories 310000 and 410000, including rhubarb) | 523 | 4 | 0.76% |
| "Kartoffeln und stärkereiche Pflanzenteile" (Potatoes and starch-rich plant parts) | 267 | 2 | 0.75% |
| "Gemüseerzeugn. und Gemüsezuber. ausgen. Rhabarber u. 200700 u. 201700" (Vegetable products and preparations excluding rhubarb and specified categories) | 289 | 2 | 0.69% |
| "Getreideprodukte Backvormischungen Brotteige Massen und Teige für" (Cereal products, baking premixes, bread doughs, mixtures and doughs) | 550 | 3 | 0.55% |
| "Getreide" (Cereals) | 456 | 2 | 0.44% |
| "Käse" (Cheese) | 264 | 1 | 0.38% |
| "Krusten- Schalen- Weichtiere sonstige Tiere u. Erzeugnisse daraus" (Crustaceans, shellfish, molluscs, other animals and derived products) | 352 | 1 | 0.28% |
| "Frischgemüse ausgenommen Rhabarber" (Fresh vegetables excluding rhubarb) | 1,817 | 3 | 0.17% |

Several product groups recorded no clearly adverse samples under the current preliminary target definition.

## Interpretation

The observed adverse rate differs noticeably between product groups.

"Gewürze" (Spices) has the highest observed adverse rate at **3.67%**, based on 14 adverse samples among 381 samples.

"Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts) and "Fleisch warmblütiger Tiere auch tiefgefroren" (Meat from warm-blooded animals, including deep-frozen products) also show rates above the overall food-scope adverse rate of **0.83%**.

In contrast, "Frischgemüse ausgenommen Rhabarber" (Fresh vegetables excluding rhubarb) represents the largest product group by sample count but has a relatively low observed adverse rate of **0.17%**.

This demonstrates that product-group frequency and adverse risk are not the same.

## Modelling Implication

"MatrixGrT" (Matrix Group Description) appears to contain potentially useful predictive information and should remain a core candidate feature.

Because it contains only **19 categories**, it is also considerably easier to encode and interpret than higher-cardinality variables such as "BetriebsartT" (Business Type Description) or "HerkStaatT" (Country of Origin Description).

The observed differences are still descriptive and do not establish causality.

In [44]:
# Chi-square test for Matrix Group Description vs Adverse Target

matrix_group_contingency = pd.crosstab(
    matrix_group_target["MatrixGrT"],
    matrix_group_target["Target_Adverse"]
)

chi2_m, p_value_m, dof_m, expected_m = chi2_contingency(
    matrix_group_contingency
)

expected_matrix_df = pd.DataFrame(
    expected_m,
    index=matrix_group_contingency.index,
    columns=matrix_group_contingency.columns
)

cells_below_5_m = (
    expected_matrix_df < 5
).sum().sum()

total_cells_m = expected_matrix_df.size

print(f"Chi-square statistic: {chi2_m:.2f}")
print(f"P-value: {p_value_m:.6f}")
print(f"Degrees of freedom: {dof_m}")
print(f"Cells with expected frequency < 5: {cells_below_5_m}")
print(f"Total contingency-table cells: {total_cells_m}")
print(
    f"Percentage of cells below 5: "
    f"{cells_below_5_m / total_cells_m * 100:.2f}%"
)

Chi-square statistic: 66.32
P-value: 0.000000
Degrees of freedom: 18
Cells with expected frequency < 5: 15
Total contingency-table cells: 38
Percentage of cells below 5: 39.47%


# Chi-Square Test for Product Group and Adverse Outcome

A chi-square test of independence was performed to investigate the relationship between "MatrixGrT" (Matrix Group Description) and the preliminary adverse target.

The hypotheses were:

**Null hypothesis (H₀):**  
Product group and adverse outcome are independent.

**Alternative hypothesis (H₁):**  
Product group and adverse outcome are associated.

## Initial Result

- Chi-square statistic: **66.32**
- p-value: **extremely small (< 0.000001 at the displayed precision)**
- Degrees of freedom: **18**
- Expected cells below 5: **15 of 38**
- Percentage of expected cells below 5: **39.47%**

## Interpretation

The calculated chi-square statistic indicates substantial differences between the observed and expected distributions of adverse outcomes across product groups.

The calculated p-value is extremely small.

However, **39.47% of the expected contingency-table cells have expected frequencies below 5**. This indicates that the conventional chi-square approximation still has an important assumption limitation.

Therefore, the small p-value should not be used by itself as definitive evidence of an association.

The result provides strong exploratory evidence that "MatrixGrT" (Matrix Group Description) may be related to adverse outcome, but the statistical conclusion requires caution because of sparse adverse observations.

## Comparison With Other Candidate Predictors

"MatrixGrT" (Matrix Group Description) is nevertheless particularly promising because:

- it contains only **19 food-related categories**;
- substantial differences in observed adverse rates exist between product groups;
- it is directly interpretable from a food-safety perspective;
- it is considerably less sparse than "HerkStaatT" (Country of Origin Description) and "BetriebsartT" (Business Type Description).

"MatrixGrT" (Matrix Group Description) will therefore remain a core candidate predictor for the machine-learning stage.

In [45]:
# Distribution of specific Matrix Description
# at the food-sample level

matrix_distribution = (
    sample_features_raw[
        ["ProbenNrPseud", "MatrixT"]
    ]
    .drop_duplicates()
    ["MatrixT"]
    .value_counts()
    .to_frame(name="Sample_Count")
)

matrix_distribution["Percentage"] = (
    matrix_distribution["Sample_Count"]
    / len(food_sample_ids)
    * 100
).round(2)

matrix_distribution.head(20)

,Sample_Count,Percentage
MatrixT,,
Pfeffer schwarz Fruchtgewürz,357,4.16
Mohrrübe; Karotte; Möhre,353,4.11
Dattel getrocknet,291,3.39
Birne,258,3.01
Blumenkohl,238,2.77
Zitrone,231,2.69
Gurke,226,2.63
Feldsalat,222,2.59
Erdnuss geröstet mit Schale,220,2.56


# Distribution of Specific Food Products

The distribution of "MatrixT" (Matrix Description) was examined at the food-sample level.

While "MatrixGrT" (Matrix Group Description) represents broad food groups, "MatrixT" (Matrix Description) identifies more specific food products.

The food-scope dataset contains **120 unique specific product categories**.

## Most Frequently Sampled Products

| Specific Product | Samples | Percentage |
|---|---:|---:|
| "Pfeffer schwarz Fruchtgewürz" (Black pepper, fruit spice) | 357 | 4.16% |
| "Mohrrübe; Karotte; Möhre" (Carrot) | 353 | 4.11% |
| "Dattel getrocknet" (Dried date) | 291 | 3.39% |
| "Birne" (Pear) | 258 | 3.01% |
| "Blumenkohl" (Cauliflower) | 238 | 2.77% |
| "Zitrone" (Lemon) | 231 | 2.69% |
| "Gurke" (Cucumber) | 226 | 2.63% |
| "Feldsalat" (Lamb's lettuce) | 222 | 2.59% |
| "Erdnuss geröstet mit Schale" (Roasted peanut with shell) | 220 | 2.56% |
| "Kürbis" (Pumpkin) | 216 | 2.52% |
| "Zwiebel" (Onion) | 211 | 2.46% |
| "Leber Rind auch tiefgefroren" (Beef liver, including deep-frozen) | 207 | 2.41% |
| "Orange" (Orange) | 203 | 2.37% |
| "Johannisbeere rot" (Red currant) | 200 | 2.33% |
| "Kiwi" (Kiwi) | 193 | 2.25% |
| "Bohne weiß" (White bean) | 191 | 2.23% |
| "Fleischteilstück Wildschwein auch tiefgefroren" (Wild-boar meat cut, including deep-frozen) | 186 | 2.17% |
| "Süßkirsche" (Sweet cherry) | 180 | 2.10% |
| "Endivie" (Endive) | 179 | 2.09% |
| "Langkornreis" (Long-grain rice) | 175 | 2.04% |

## Interpretation

The sample population covers a broad range of specific food products.

No single "MatrixT" (Matrix Description) category dominates the dataset. The most frequently sampled specific product, "Pfeffer schwarz Fruchtgewürz" (Black pepper, fruit spice), represents only **4.16%** of food samples.

This indicates considerably greater product-level diversity than is visible from the broader "MatrixGrT" (Matrix Group Description) variable.

## Feature-Engineering Implication

"MatrixT" (Matrix Description) may provide more detailed predictive information than the broader product-group variable.

However, its **120 categories** also create greater categorical complexity.

Because "MatrixT" (Matrix Description) is a more detailed representation of "MatrixGrT" (Matrix Group Description), the relationship between these two variables will also need to be considered during modelling to avoid unnecessary redundancy.

Both variables will initially remain candidate predictors.

In [46]:
# Compare specific Matrix Description
# with the preliminary adverse target

matrix_target = (
    sample_features_raw[
        ["ProbenNrPseud", "MatrixT"]
    ]
    .drop_duplicates()
)

matrix_target["Target_Adverse"] = (
    matrix_target["ProbenNrPseud"]
    .isin(food_adverse_samples)
    .astype(int)
)

matrix_risk = (
    matrix_target
    .groupby("MatrixT")
    .agg(
        Total_Samples=("ProbenNrPseud", "nunique"),
        Adverse_Samples=("Target_Adverse", "sum")
    )
)

matrix_risk["Adverse_Rate_Percent"] = (
    matrix_risk["Adverse_Samples"]
    / matrix_risk["Total_Samples"]
    * 100
).round(2)

# Show products with at least 30 samples
matrix_risk_reliable = (
    matrix_risk[
        matrix_risk["Total_Samples"] >= 30
    ]
    .sort_values(
        ["Adverse_Rate_Percent", "Adverse_Samples"],
        ascending=False
    )
)

matrix_risk_reliable.head(20)

,Total_Samples,Adverse_Samples,Adverse_Rate_Percent
MatrixT,,,
Sauerkirsche tiefgefroren,32,4,12.50
Erdnuss geröstet mit Schale,220,8,3.64
Süßkirsche,180,6,3.33
Pfeffer schwarz Fruchtgewürz,357,11,3.08
Miesmuschelerzeugnisse,34,1,2.94
Parmigiano Reggiano Hartkäse andere,42,1,2.38
Kartoffel früh,43,1,2.33
Roggenvollkornmehl,138,3,2.17
Brust Ente auch tiefgefroren,46,1,2.17


# Specific Food Products and Observed Adverse Rate

The relationship between "MatrixT" (Matrix Description) and the preliminary adverse target was examined at the food-sample level.

For descriptive interpretation, the displayed ranking was restricted to specific food products with at least **30 samples**.

## Highest Observed Adverse Rates

| Specific Product | Total Samples | Adverse Samples | Observed Adverse Rate |
|---|---:|---:|---:|
| "Sauerkirsche tiefgefroren" (Deep-frozen sour cherry) | 32 | 4 | 12.50% |
| "Erdnuss geröstet mit Schale" (Roasted peanut with shell) | 220 | 8 | 3.64% |
| "Süßkirsche" (Sweet cherry) | 180 | 6 | 3.33% |
| "Pfeffer schwarz Fruchtgewürz" (Black pepper, fruit spice) | 357 | 11 | 3.08% |
| "Miesmuschelerzeugnisse" (Mussel products) | 34 | 1 | 2.94% |
| "Parmigiano Reggiano Hartkäse andere" (Parmigiano Reggiano hard cheese, other) | 42 | 1 | 2.38% |
| "Kartoffel früh" (Early potato) | 43 | 1 | 2.33% |
| "Roggenvollkornmehl" (Whole-grain rye flour) | 138 | 3 | 2.17% |
| "Brust Ente auch tiefgefroren" (Duck breast, including deep-frozen) | 46 | 1 | 2.17% |
| "Bohne weiß" (White bean) | 191 | 4 | 2.09% |
| "Leber Rind auch tiefgefroren" (Beef liver, including deep-frozen) | 207 | 4 | 1.93% |
| "Fleischteilstück Ente auch tiefgefroren" (Duck meat cut, including deep-frozen) | 56 | 1 | 1.79% |
| "Fleischteilstück Wildschwein auch tiefgefroren" (Wild-boar meat cut, including deep-frozen) | 186 | 3 | 1.61% |

## Interpretation

The specific product-level analysis reveals more detailed patterns than the broad "MatrixGrT" (Matrix Group Description) analysis.

"Schwarzer Pfeffer" (Black pepper) and "Erdnuss geröstet mit Schale" (Roasted peanut with shell) account for relatively large numbers of adverse samples and may help explain the elevated adverse rates observed in their broader product groups.

"Deep-frozen sour cherry" shows the highest observed rate at **12.50%**, but this is based on only **4 adverse samples among 32 samples**. This estimate is therefore less stable and should be interpreted cautiously.

The results again demonstrate the difference between a high observed percentage and strong statistical evidence.

## Feature-Engineering Implication

"MatrixT" (Matrix Description) may contain useful predictive detail beyond "MatrixGrT" (Matrix Group Description).

However, because "MatrixT" (Matrix Description) is a more granular representation of the broader matrix group, including both variables in a model may introduce redundancy.

Their relative predictive contribution should therefore be evaluated during modelling rather than assuming that both are automatically required.

In [47]:
# Check relationship between specific Matrix Description
# and broad Matrix Group Description

matrix_hierarchy = (
    sample_features_raw[
        ["MatrixT", "MatrixGrT"]
    ]
    .drop_duplicates()
    .groupby("MatrixT")["MatrixGrT"]
    .nunique()
)

print(
    "Specific products linked to exactly one matrix group:",
    (matrix_hierarchy == 1).sum()
)

print(
    "Specific products linked to multiple matrix groups:",
    (matrix_hierarchy > 1).sum()
)

print(
    "Maximum number of matrix groups for one specific product:",
    matrix_hierarchy.max()
)

Specific products linked to exactly one matrix group: 120
Specific products linked to multiple matrix groups: 0
Maximum number of matrix groups for one specific product: 1


# Hierarchical Relationship Between Product Variables

The relationship between "MatrixT" (Matrix Description) and "MatrixGrT" (Matrix Group Description) was examined.

The analysis produced the following results:

- Specific products linked to exactly one matrix group: **120**
- Specific products linked to multiple matrix groups: **0**
- Maximum matrix groups associated with a specific product: **1**

## Interpretation

Every specific "MatrixT" (Matrix Description) category belongs to exactly one "MatrixGrT" (Matrix Group Description).

This confirms a clear hierarchical relationship:

**"MatrixGrT" (Matrix Group Description) → "MatrixT" (Matrix Description)**

The broad matrix group therefore represents a higher-level classification, while the matrix description provides a more detailed product classification.

## Modelling Implication

Because "MatrixT" (Matrix Description) is completely nested within "MatrixGrT" (Matrix Group Description), the two variables contain overlapping information.

Both variables will initially remain candidate predictors, but their contribution should be compared during modelling.

Possible model configurations include:

1. using only "MatrixGrT" (Matrix Group Description);
2. using only "MatrixT" (Matrix Description);
3. using both variables.

Cross-validation and appropriate imbalanced-classification metrics will later determine whether the additional product-level detail improves prediction.

In [48]:
# Inspect Sampling Date before conversion

sample_dates = (
    sample_features_raw[
        ["ProbenNrPseud", "PNDat"]
    ]
    .drop_duplicates()
)

print("Number of sample-date records:", len(sample_dates))
print("Missing dates:", sample_dates["PNDat"].isna().sum())

print("\nFirst 10 original date values:")
print(sample_dates["PNDat"].head(10))

Number of sample-date records: 8582
Missing dates: 0

First 10 original date values:
0    28AUG2023:00:00:00
1    28SEP2023:00:00:00
2    16NOV2023:00:00:00
3    10OCT2023:00:00:00
4    25APR2023:00:00:00
5    10MAY2023:00:00:00
6    24OCT2023:00:00:00
7    15MAY2023:00:00:00
8    20JAN2023:00:00:00
9    19OCT2023:00:00:00
Name: PNDat, dtype: str


# Sampling Date Data Quality

The variable "PNDat" (Sampling Date) was examined at the sample level.

The analysis identified:

- **8,582 sample-date records**
- **0 missing sampling dates**
- one sampling date for each food-scope sample

The original values are stored as text using a format such as:

"28AUG2023:00:00:00"

This represents 28 August 2023.

## Interpretation

"PNDat" (Sampling Date) has complete coverage across the food-scope dataset and therefore does not require missing-value treatment.

However, the variable is currently stored as a string rather than as a datetime variable.

It will therefore be converted to a proper datetime format before further analysis.

## Feature-Engineering Potential

The raw sampling date itself will not necessarily be used directly as a machine-learning predictor.

Instead, useful temporal features can potentially be derived, including:

- sampling month;
- sampling quarter;
- season.

These features may help determine whether the observed adverse rate varies over the course of the year.

In [49]:
# Convert PNDat (Sampling Date) from text to datetime

sample_dates["Sampling_Date"] = pd.to_datetime(
    sample_dates["PNDat"],
    format="%d%b%Y:%H:%M:%S"
)

print(sample_dates[["PNDat", "Sampling_Date"]].head(10))

print("\nConverted data type:")
print(sample_dates["Sampling_Date"].dtype)

print("\nEarliest sampling date:")
print(sample_dates["Sampling_Date"].min())

print("\nLatest sampling date:")
print(sample_dates["Sampling_Date"].max())

print("\nFailed conversions:")
print(sample_dates["Sampling_Date"].isna().sum())

                PNDat Sampling_Date
0  28AUG2023:00:00:00    2023-08-28
1  28SEP2023:00:00:00    2023-09-28
2  16NOV2023:00:00:00    2023-11-16
3  10OCT2023:00:00:00    2023-10-10
4  25APR2023:00:00:00    2023-04-25
5  10MAY2023:00:00:00    2023-05-10
6  24OCT2023:00:00:00    2023-10-24
7  15MAY2023:00:00:00    2023-05-15
8  20JAN2023:00:00:00    2023-01-20
9  19OCT2023:00:00:00    2023-10-19

Converted data type:
datetime64[us]

Earliest sampling date:
2023-01-02 00:00:00

Latest sampling date:
2023-12-21 00:00:00

Failed conversions:
0


# Sampling Date Conversion

"PNDat" (Sampling Date) was successfully converted from its original text format into a pandas datetime variable named "Sampling_Date" (Sampling Date).

## Conversion Results

- Food-scope samples: **8,582**
- Successfully converted dates: **8,582**
- Failed conversions: **0**
- Earliest sampling date: **2 January 2023**
- Latest sampling date: **21 December 2023**
- Converted data type: **datetime64**

## Interpretation

The conversion confirms that "PNDat" (Sampling Date) is complete and consistently formatted across the food-scope dataset.

The sampling period covers almost the entire 2023 calendar year, allowing temporal patterns in sampling and adverse outcomes to be investigated.

Rather than using the exact calendar date directly as a categorical predictor, meaningful temporal characteristics can be derived from it, such as sampling month, quarter, and season.

In [50]:
# Derive sampling month

sample_dates["Sampling_Month"] = (
    sample_dates["Sampling_Date"].dt.month
)

sample_dates["Sampling_Month_Name"] = (
    sample_dates["Sampling_Date"].dt.month_name()
)

monthly_distribution = (
    sample_dates
    .groupby(
        ["Sampling_Month", "Sampling_Month_Name"]
    )
    .size()
    .reset_index(name="Sample_Count")
    .sort_values("Sampling_Month")
)

monthly_distribution["Percentage"] = (
    monthly_distribution["Sample_Count"]
    / len(sample_dates)
    * 100
).round(2)

monthly_distribution

,Sampling_Month,Sampling_Month_Name,Sample_Count,Percentage
0,1,January,943,10.99
1,2,February,970,11.30
2,3,March,796,9.28
3,4,April,676,7.88
4,5,May,698,8.13
5,6,June,790,9.21
6,7,July,1050,12.23
7,8,August,685,7.98
8,9,September,772,9.00
9,10,October,661,7.70


# Monthly Distribution of Food Samples

The sampling month was derived from "PNDat" (Sampling Date) and examined across the **8,582 food-scope samples**.

## Monthly Sample Distribution

| Month | Samples | Percentage |
|---|---:|---:|
| January | 943 | 10.99% |
| February | 970 | 11.30% |
| March | 796 | 9.28% |
| April | 676 | 7.88% |
| May | 698 | 8.13% |
| June | 790 | 9.21% |
| July | 1,050 | 12.23% |
| August | 685 | 7.98% |
| September | 772 | 9.00% |
| October | 661 | 7.70% |
| November | 410 | 4.78% |
| December | 131 | 1.53% |

## Interpretation

Food samples were collected throughout the entire 2023 calendar year, but sampling activity was not evenly distributed across months.

July recorded the largest number of samples, with **1,050 samples (12.23%)**.

Sampling was also relatively high in January and February.

In contrast, sampling activity decreased substantially toward the end of the year, particularly in November and December. December contained only **131 samples (1.53%)**.

This uneven sampling distribution is important when comparing adverse outcomes over time. Raw adverse counts should therefore not be compared between months without also considering the number of samples collected in each month.

Monthly adverse **rates**, rather than adverse counts alone, will provide a more meaningful temporal comparison.

In [51]:
# Add the preliminary adverse target to the monthly sample data

sample_dates["Target_Adverse"] = (
    sample_dates["ProbenNrPseud"]
    .isin(food_adverse_samples)
    .astype(int)
)

monthly_risk = (
    sample_dates
    .groupby(
        ["Sampling_Month", "Sampling_Month_Name"]
    )
    .agg(
        Total_Samples=("ProbenNrPseud", "nunique"),
        Adverse_Samples=("Target_Adverse", "sum")
    )
    .reset_index()
    .sort_values("Sampling_Month")
)

monthly_risk["Adverse_Rate_Percent"] = (
    monthly_risk["Adverse_Samples"]
    / monthly_risk["Total_Samples"]
    * 100
).round(2)

monthly_risk

,Sampling_Month,Sampling_Month_Name,Total_Samples,Adverse_Samples,Adverse_Rate_Percent
0,1,January,943,7,0.74
1,2,February,970,6,0.62
2,3,March,796,8,1.01
3,4,April,676,2,0.30
4,5,May,698,5,0.72
5,6,June,790,14,1.77
6,7,July,1050,13,1.24
7,8,August,685,2,0.29
8,9,September,772,5,0.65
9,10,October,661,9,1.36


# Monthly Variation in Observed Adverse Outcomes

The monthly distribution of the preliminary adverse target was examined across the **8,582 food-scope samples**.

The overall food-scope adverse rate is approximately **0.83%**.

## Monthly Adverse Rates

| Month | Total Samples | Adverse Samples | Adverse Rate |
|---|---:|---:|---:|
| January | 943 | 7 | 0.74% |
| February | 970 | 6 | 0.62% |
| March | 796 | 8 | 1.01% |
| April | 676 | 2 | 0.30% |
| May | 698 | 5 | 0.72% |
| June | 790 | 14 | 1.77% |
| July | 1,050 | 13 | 1.24% |
| August | 685 | 2 | 0.29% |
| September | 772 | 5 | 0.65% |
| October | 661 | 9 | 1.36% |
| November | 410 | 0 | 0.00% |
| December | 131 | 0 | 0.00% |

## Interpretation

Observed adverse rates vary across the months of 2023.

"June" has the highest observed adverse rate at **1.77%**, with 14 adverse samples among 790 samples.

This is followed by "October" at **1.36%** and "July" at **1.24%**.

In contrast, "November" and "December" contain no clearly adverse samples under the current preliminary target definition.

The absence of adverse samples in these months should not be interpreted as evidence of zero food-safety risk. In particular, December contains only **131 samples**, resulting in considerably less evidence than months with larger sample sizes.

June and July together account for **27 of the 71 adverse food samples**, indicating a concentration of observed adverse outcomes during this period.

## Modelling Implication

Sampling month may contain potentially useful predictive information.

However, the observed monthly differences may also reflect changes in:

- the types of food sampled during different months;
- countries of origin;
- monitoring programmes;
- business types;
- analytical parameters.

Therefore, the monthly pattern should be treated as an association rather than evidence that the month itself causes adverse outcomes.

The usefulness of temporal information will later be evaluated together with the other predictors in the machine-learning models.

In [52]:
# Add sampling month to the sample-level feature data

month_product = (
    sample_features_raw[
        ["ProbenNrPseud", "MatrixGrT"]
    ]
    .drop_duplicates()
    .merge(
        sample_dates[
            ["ProbenNrPseud", "Sampling_Month"]
        ],
        on="ProbenNrPseud",
        how="left"
    )
)

# Product-group distribution for June
june_product_distribution = (
    month_product[
        month_product["Sampling_Month"] == 6
    ]
    ["MatrixGrT"]
    .value_counts()
    .to_frame(name="June_Samples")
)

june_product_distribution["June_Percentage"] = (
    june_product_distribution["June_Samples"]
    / june_product_distribution["June_Samples"].sum()
    * 100
).round(2)

june_product_distribution

,June_Samples,June_Percentage
MatrixGrT,,
Frischgemüse ausgenommen Rhabarber,196,24.81
Frischobst einschließlich Rhabarber,129,16.33
Hülsenfrüchte Ölsamen Schalenobst,96,12.15
Gewürze,56,7.09
Getreideprodukte Backvormischungen Brotteige Massen und Teige für,53,6.71
Fleisch warmblütiger Tiere auch tiefgefroren,47,5.95
Gemüseerzeugn. und Gemüsezuber. ausgen. Rhabarber u. 200700 u. 201700,39,4.94
Krusten- Schalen- Weichtiere sonstige Tiere u. Erzeugnisse daraus,31,3.92
Säuglings- und Kleinkindernahrungen,31,3.92


# Product-Group Composition of June Samples

June had the highest observed monthly adverse rate at **1.77%**.

To investigate whether this could partly reflect the types of food sampled during the month, the product-group composition of June was examined.

## Main Product Groups Sampled in June

The largest product groups were:

- "Frischgemüse ausgenommen Rhabarber" (Fresh vegetables excluding rhubarb): **196 samples, 24.81%**
- "Frischobst einschließlich Rhabarber" (Fresh fruit including rhubarb): **129 samples, 16.33%**
- "Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts): **96 samples, 12.15%**
- "Gewürze" (Spices): **56 samples, 7.09%**
- "Getreideprodukte Backvormischungen Brotteige Massen und Teige für" (Cereal products, baking premixes, bread doughs, mixtures and doughs): **53 samples, 6.71%**
- "Fleisch warmblütiger Tiere auch tiefgefroren" (Meat from warm-blooded animals, including deep-frozen products): **47 samples, 5.95%**

## Interpretation

June contains substantial numbers of several product groups that previously showed above-average observed adverse rates, including "Gewürze" (Spices), "Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts), and meat products.

However, the largest June category is "Frischgemüse ausgenommen Rhabarber" (Fresh vegetables excluding rhubarb), which had a relatively low overall observed adverse rate.

Therefore, June's elevated adverse rate cannot be attributed solely to the presence of generally higher-risk product groups.

The monthly pattern may instead reflect a combination of:

- product mix;
- specific products within those groups;
- country of origin;
- monitoring programme;
- business type;
- analytical testing patterns.

This reinforces the need for multivariable modelling rather than interpreting the month effect in isolation.

In [53]:
# Identify the product groups responsible for June adverse samples

june_adverse_groups = (
    month_product[
        (month_product["Sampling_Month"] == 6)
        & (
            month_product["ProbenNrPseud"]
            .isin(food_adverse_samples)
        )
    ]
    ["MatrixGrT"]
    .value_counts()
    .to_frame(name="June_Adverse_Samples")
)

june_adverse_groups

,June_Adverse_Samples
MatrixGrT,
Gewürze,5
Hülsenfrüchte Ölsamen Schalenobst,5
Frischobst einschließlich Rhabarber,3
Kartoffeln und stärkereiche Pflanzenteile,1


# Product Groups Responsible for June Adverse Outcomes

June recorded **14 clearly adverse food samples**, representing the highest number of adverse samples and the highest observed monthly adverse rate of **1.77%**.

The adverse samples were concentrated in only four "MatrixGrT" (Matrix Group Description) categories:

| Product Group | June Adverse Samples |
|---|---:|
| "Gewürze" (Spices) | 5 |
| "Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts) | 5 |
| "Frischobst einschließlich Rhabarber" (Fresh fruit including rhubarb) | 3 |
| "Kartoffeln und stärkereiche Pflanzenteile" (Potatoes and starch-rich plant parts) | 1 |

## Interpretation

The June adverse outcomes were strongly concentrated within a small number of product groups.

"Gewürze" (Spices) and "Hülsenfrüchte Ölsamen Schalenobst" (Legumes, oilseeds and nuts) together accounted for **10 of the 14 adverse samples**, or approximately **71.4%** of all adverse samples recorded in June.

This is consistent with the earlier product-group analysis, where these groups showed relatively high overall observed adverse rates.

The result suggests that the elevated June adverse rate may be influenced substantially by the particular food products sampled during that period.

Therefore, the observed monthly pattern should not be interpreted as evidence that the month itself causes higher food-safety risk.

Instead, month and product type may be associated, and multivariable modelling will help determine whether temporal information provides additional predictive value after product characteristics are considered.

In [54]:
# Inspect samples with multiple Processing Description values

processing_per_sample = (
    sample_features_raw[
        ["ProbenNrPseud", "VerarbeitungT"]
    ]
    .dropna()
    .drop_duplicates()
    .groupby("ProbenNrPseud")["VerarbeitungT"]
    .agg(list)
)

multiple_processing = processing_per_sample[
    processing_per_sample.apply(len) > 1
]

print("Samples with multiple processing descriptions:",
      len(multiple_processing))

multiple_processing.head(15)

Samples with multiple processing descriptions: 95


ProbenNrPseud
192     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
312     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
323     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
326     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
403     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
482     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
483     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
646                   [Entsteint/entstielt, Keine Angabe]
730     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
884     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
934     [Verzehrsfertig/tischfertig vor-/zubereitet, G...
1096    [Verzehrsfertig/tischfertig vor-/zubereitet, G...
1272    [Verzehrsfertig/tischfertig vor-/zubereitet, G...
1303    [Verzehrsfertig/tischfertig vor-/zubereitet, G...
1374    [Verzehrsfertig/tischfertig vor-/zubereitet, G...
Name: VerarbeitungT, dtype: object

# Multiple Processing Descriptions per Sample

"VerarbeitungT" (Processing Description) is not completely constant at the sample level.

Among the food-scope samples:

- **8,409 samples** have exactly one non-missing processing description;
- **95 samples** contain multiple processing descriptions;
- **78 samples** have no processing description.

Inspection of the multi-valued samples confirms that some samples genuinely contain more than one processing-related category.

Therefore, arbitrarily selecting the first available "VerarbeitungT" (Processing Description) value could result in information loss or misrepresentation.

The combinations will be examined before deciding how this variable should be represented in the sample-level modelling dataset.

In [55]:
# Examine the most common combinations of Processing Description

processing_combinations = (
    multiple_processing
    .apply(lambda x: " | ".join(sorted(x)))
    .value_counts()
    .to_frame(name="Sample_Count")
)

pd.set_option("display.max_colwidth", None)

processing_combinations.head(20)


,Sample_Count
VerarbeitungT,
Getrocknet | Verzehrsfertig/tischfertig vor-/zubereitet,92
Keine Angabe | Verzehrsfertig/tischfertig vor-/zubereitet,2
Entsteint/entstielt | Keine Angabe,1


# Structure of Multiple Processing Descriptions

The 95 samples containing multiple "VerarbeitungT" (Processing Description) values were examined in greater detail.

Only three combinations were identified:

| Processing Combination | Samples |
|---|---:|
| "Getrocknet" (Dried) + "Verzehrsfertig/tischfertig vor-/zubereitet" (Ready-to-eat/table-ready prepared) | 92 |
| "Keine Angabe" (No information provided) + "Verzehrsfertig/tischfertig vor-/zubereitet" (Ready-to-eat/table-ready prepared) | 2 |
| "Entsteint/entstielt" (Pitted/destemmed) + "Keine Angabe" (No information provided) | 1 |

## Interpretation

The multiple processing descriptions do not appear to result primarily from random inconsistencies.

Of the **95 multi-valued samples, 92 (96.8%)** contain the same combination of "Getrocknet" (Dried) and "Verzehrsfertig/tischfertig vor-/zubereitet" (Ready-to-eat/table-ready prepared).

This indicates that a food sample can legitimately possess more than one processing characteristic.

Therefore, selecting only the first processing description would discard potentially meaningful information.

## Feature-Engineering Decision

For the sample-level modelling dataset, multiple genuine processing descriptions should be preserved as combined categories rather than arbitrarily selecting one value.

Missing processing information will also be retained explicitly as a separate category rather than deleting the affected samples.

This approach preserves the information contained in "VerarbeitungT" (Processing Description) while maintaining one row per food sample.

In [56]:
# Create one Processing Description feature per sample

processing_feature = (
    sample_features_raw[
        ["ProbenNrPseud", "VerarbeitungT"]
    ]
    .drop_duplicates()
    .groupby("ProbenNrPseud")["VerarbeitungT"]
    .apply(
        lambda x: " | ".join(
            sorted(x.dropna().unique())
        )
    )
    .reset_index(name="Processing_Feature")
)

# Represent samples with no processing information explicitly
processing_feature["Processing_Feature"] = (
    processing_feature["Processing_Feature"]
    .replace("", "Missing")
)

print("Number of samples:", len(processing_feature))

print("\nMissing after processing:")
print(processing_feature["Processing_Feature"].isna().sum())

print("\nNumber of resulting processing categories:")
print(processing_feature["Processing_Feature"].nunique())

print("\nMost common processing categories:")
print(
    processing_feature["Processing_Feature"]
    .value_counts()
    .head(15)
)

Number of samples: 8582

Missing after processing:
0

Number of resulting processing categories:
37

Most common processing categories:
Processing_Feature
Keine Angabe                                               3155
Unverarbeitet/roh                                          2393
Gemahlen/geschrotet                                         727
Tiefgekühlt/tiefgefroren                                    406
Getrocknet                                                  299
Ohne Haut                                                   219
Gereinigt                                                   210
Ungeschält                                                  171
Geröstet                                                    117
Entsteint/entstielt                                         116
Küchenfertig vor-/zubereitet                                 98
Getrocknet | Verzehrsfertig/tischfertig vor-/zubereitet      92
Ungeschwefelt                                                80
Missing      

# Sample-Level Processing Feature

A sample-level processing feature was created from "VerarbeitungT" (Processing Description).

The transformation preserved multiple legitimate processing descriptions by combining them into a single sample-level category.

Samples with genuinely missing processing information were explicitly represented as "Missing" (Missing).

## Transformation Results

- Food-scope samples: **8,582**
- Missing values after transformation: **0**
- Resulting processing categories: **37**

The most frequent processing categories include:

| Processing Description | Samples |
|---|---:|
| "Keine Angabe" (No information provided) | 3,155 |
| "Unverarbeitet/roh" (Unprocessed/raw) | 2,393 |
| "Gemahlen/geschrotet" (Ground/crushed) | 727 |
| "Tiefgekühlt/tiefgefroren" (Deep-frozen/frozen) | 406 |
| "Getrocknet" (Dried) | 299 |
| "Ohne Haut" (Without skin) | 219 |
| "Gereinigt" (Cleaned) | 210 |
| "Ungeschält" (Unpeeled) | 171 |
| "Geröstet" (Roasted) | 117 |
| "Entsteint/entstielt" (Pitted/destemmed) | 116 |
| "Küchenfertig vor-/zubereitet" (Kitchen-ready prepared) | 98 |
| "Getrocknet | Verzehrsfertig/tischfertig vor-/zubereitet" (Dried | Ready-to-eat/table-ready prepared) | 92 |
| "Ungeschwefelt" (Unsulphured) | 80 |
| "Missing" (Missing) | 78 |
| "Verzehrsfertig/tischfertig vor-/zubereitet" (Ready-to-eat/table-ready prepared) | 64 |

## Important Distinction

"Keine Angabe" (No information provided) and "Missing" (Missing) are retained as separate categories.

"Keine Angabe" (No information provided) is an explicit category recorded in the original BVL data.

"Missing" (Missing), in contrast, represents samples for which no "VerarbeitungT" (Processing Description) value was available.

Combining these categories would remove this distinction and potentially discard useful information.

## Modelling Implication

The newly created "Processing_Feature" (Processing Feature) provides exactly one processing representation per food sample and can therefore be incorporated into the sample-level modelling dataset.

Categorical encoding will be performed later as part of the machine-learning preprocessing pipeline and will be fitted using the training data only.

In [57]:
# Create one Packaging Description feature per sample

packaging_feature = (
    sample_features_raw[
        ["ProbenNrPseud", "VerpackungT"]
    ]
    .drop_duplicates()
    .groupby("ProbenNrPseud")["VerpackungT"]
    .first()
    .reindex(sorted(food_sample_ids))
    .reset_index()
    .rename(columns={"VerpackungT": "Packaging_Feature"})
)

# Preserve missing packaging information explicitly
packaging_feature["Packaging_Feature"] = (
    packaging_feature["Packaging_Feature"]
    .fillna("Missing")
)

print("Number of samples:", len(packaging_feature))

print("\nMissing after processing:")
print(packaging_feature["Packaging_Feature"].isna().sum())

print("\nNumber of packaging categories:")
print(packaging_feature["Packaging_Feature"].nunique())

print("\nMost common packaging categories:")
print(
    packaging_feature["Packaging_Feature"]
    .value_counts()
    .head(15)
)

Number of samples: 8582

Missing after processing:
0

Number of packaging categories:
32

Most common packaging categories:
Packaging_Feature
Kunststoff/-folie                             3075
Keine Angabe                                  2012
Verpackt                                       911
Unverpackt                                     751
Papier                                         420
Gewebe aus Kunstfaser                          266
Kombinationsverpackung aus Pappe und Folie     259
Karton/Pappe                                   193
Umhüllt                                        121
Glas                                            91
Glas farblos                                    78
Kunststoffverbundfolie                          68
Verpackt unter Vakuum                           58
Verbundmaterial                                 49
Missing                                         32
Name: count, dtype: int64


# Sample-Level Packaging Feature

A sample-level packaging feature was created from "VerpackungT" (Packaging Description).

Unlike "VerarbeitungT" (Processing Description), no food sample contained multiple packaging descriptions. Therefore, the variable could be represented directly at the sample level.

## Transformation Results

- Food-scope samples: **8,582**
- Missing values after transformation: **0**
- Resulting packaging categories: **32**

The most frequent packaging categories include:

| Packaging Description | Samples |
|---|---:|
| "Kunststoff/-folie" (Plastic/plastic film) | 3,075 |
| "Keine Angabe" (No information provided) | 2,012 |
| "Verpackt" (Packaged) | 911 |
| "Unverpackt" (Unpackaged) | 751 |
| "Papier" (Paper) | 420 |
| "Gewebe aus Kunstfaser" (Synthetic-fibre fabric) | 266 |
| "Kombinationsverpackung aus Pappe und Folie" (Combined cardboard and film packaging) | 259 |
| "Karton/Pappe" (Cardboard/paperboard) | 193 |
| "Umhüllt" (Wrapped) | 121 |
| "Glas" (Glass) | 91 |
| "Glas farblos" (Colourless glass) | 78 |
| "Kunststoffverbundfolie" (Composite plastic film) | 68 |
| "Verpackt unter Vakuum" (Vacuum-packed) | 58 |
| "Verbundmaterial" (Composite material) | 49 |
| "Missing" (Missing) | 32 |

## Important Distinction

"Keine Angabe" (No information provided) is an explicit category in the original BVL dataset, whereas "Missing" (Missing) represents an actual absence of packaging information.

The two categories are therefore retained separately.

## Modelling Implication

"Packaging_Feature" (Packaging Feature) now provides exactly one packaging representation for every food-scope sample and can be incorporated into the sample-level modelling dataset.

Categorical encoding will be performed later within the machine-learning preprocessing pipeline using training data only.

In [58]:
# Inspect samples with multiple Country of Origin values

country_per_sample = (
    sample_features_raw[
        ["ProbenNrPseud", "HerkStaatT"]
    ]
    .dropna()
    .drop_duplicates()
    .groupby("ProbenNrPseud")["HerkStaatT"]
    .agg(list)
)

multiple_countries = country_per_sample[
    country_per_sample.apply(len) > 1
]

print(
    "Samples with multiple countries of origin:",
    len(multiple_countries)
)

multiple_countries

Samples with multiple countries of origin: 2


ProbenNrPseud
3692                            [Vietnam, Ungeklärt]
7835    [Indien, einschl. Sikkim und Goa, Ungeklärt]
Name: HerkStaatT, dtype: object

# Resolution of Multiple Country-of-Origin Values

The sample-level consistency assessment identified only **2 of 8,582 food-scope samples** with multiple values for "HerkStaatT" (Country of Origin Description).

The two cases were:

- Sample 3692: "Vietnam" (Vietnam) and "Ungeklärt" (Unresolved/Unknown)
- Sample 7835: "Indien, einschl. Sikkim und Goa" (India, including Sikkim and Goa) and "Ungeklärt" (Unresolved/Unknown)

## Data-Cleaning Decision

In both cases, a specific country of origin is available alongside "Ungeklärt" (Unresolved/Unknown).

The specific country is therefore retained as the sample-level country-of-origin value.

This approach prioritizes the available informative value without introducing information that is not present in the original dataset.

No food samples are removed as a result of this issue.

In [59]:
# Create one Country of Origin feature per sample

def resolve_country(values):
    values = list(values.dropna().unique())

    # If a specific country exists together with
    # Ungeklärt (Unresolved/Unknown), keep the specific country
    specific_values = [
        value for value in values
        if value != "Ungeklärt"
    ]

    if len(specific_values) == 1:
        return specific_values[0]

    if len(values) == 1:
        return values[0]

    if len(values) == 0:
        return "Missing"

    # Safety fallback if another unexpected combination exists
    return " | ".join(sorted(values))


country_feature = (
    sample_features_raw[
        ["ProbenNrPseud", "HerkStaatT"]
    ]
    .drop_duplicates()
    .groupby("ProbenNrPseud")["HerkStaatT"]
    .apply(resolve_country)
    .reindex(sorted(food_sample_ids))
    .reset_index(name="Country_Feature")
)

print("Number of samples:", len(country_feature))

print("\nMissing after processing:")
print(country_feature["Country_Feature"].isna().sum())

print("\nNumber of country categories:")
print(country_feature["Country_Feature"].nunique())

print("\nResolved multi-valued samples:")
print(
    country_feature[
        country_feature["ProbenNrPseud"].isin([3692, 7835])
    ]
)

Number of samples: 8582

Missing after processing:
0

Number of country categories:
87

Resolved multi-valued samples:
      ProbenNrPseud                  Country_Feature
3233           3692                          Vietnam
6919           7835  Indien, einschl. Sikkim und Goa


# Final Sample-Level Country-of-Origin Feature

A clean sample-level country-of-origin feature was created from "HerkStaatT" (Country of Origin Description).

## Transformation Results

- Food-scope samples: **8,582**
- Missing values after processing: **0**
- Unique country-of-origin categories: **87**

The two samples containing both a specific country and "Ungeklärt" (Unresolved/Unknown) were resolved by retaining the more informative specific country:

- Sample 3692 → "Vietnam" (Vietnam)
- Sample 7835 → "Indien, einschl. Sikkim und Goa" (India, including Sikkim and Goa)

No samples were removed during this transformation.

## Modelling Implication

"Country_Feature" (Country Feature) now provides exactly one country-of-origin representation for every food-scope sample.

Because the variable contains **87 categories**, rare-category handling and categorical encoding will later be performed within the machine-learning preprocessing workflow using the training data only.

In [60]:
# Build the preliminary one-row-per-sample modelling dataset

base_features = (
    sample_features_raw[
        [
            "ProbenNrPseud",
            "PnMgT",
            "MatrixGrT",
            "MatrixT",
            "BetriebsartT"
        ]
    ]
    .drop_duplicates()
)

model_df = (
    sample_target
    .merge(
        base_features,
        on="ProbenNrPseud",
        how="left"
    )
    .merge(
        country_feature,
        on="ProbenNrPseud",
        how="left"
    )
    .merge(
        processing_feature,
        on="ProbenNrPseud",
        how="left"
    )
    .merge(
        packaging_feature,
        on="ProbenNrPseud",
        how="left"
    )
    .merge(
        sample_dates[
            [
                "ProbenNrPseud",
                "Sampling_Date",
                "Sampling_Month"
            ]
        ],
        on="ProbenNrPseud",
        how="left"
    )
)

print("Model dataset shape:", model_df.shape)

print("\nTarget distribution:")
print(model_df["Target_Adverse"].value_counts())

print("\nDuplicate sample IDs:")
print(model_df["ProbenNrPseud"].duplicated().sum())

print("\nMissing values by column:")
print(model_df.isna().sum())

model_df.head()

Model dataset shape: (8582, 11)

Target distribution:
Target_Adverse
0    8511
1      71
Name: count, dtype: int64

Duplicate sample IDs:
0

Missing values by column:
ProbenNrPseud         0
Target_Adverse        0
PnMgT                 0
MatrixGrT             0
MatrixT               0
BetriebsartT          0
Country_Feature       0
Processing_Feature    0
Packaging_Feature     0
Sampling_Date         0
Sampling_Month        0
dtype: int64


,ProbenNrPseud,Target_Adverse,PnMgT,MatrixGrT,MatrixT,BetriebsartT,Country_Feature,Processing_Feature,Packaging_Feature,Sampling_Date,Sampling_Month
0,2,0,Monitoring-Planprobe,Hülsenfrüchte Ölsamen Schalenobst,Leinsamen aufgebrochen/geschrotet,Lebensmittelgeschäft und (eigenständige) -verkaufsabteilung (incl. Supermarkt),Ungeklärt,Gemahlen/geschrotet,Verpackt,2023-08-28,8
1,3,0,EG(KKP)- und Monitoring-Planprobe,Frischgemüse ausgenommen Rhabarber,Blumenkohl,Lebensmittelgeschäft und (eigenständige) -verkaufsabteilung (incl. Supermarkt),Deutschland,Unverarbeitet/roh,Unverpackt,2023-09-28,9
2,4,0,Monitoring-Planprobe,Obstprodukte ausgenommen 310000 und 410000 einschl. Rhabarber,Dattel getrocknet,Lebensmittelgeschäft und (eigenständige) -verkaufsabteilung (incl. Supermarkt),Algerien,Getrocknet,Karton/Pappe,2023-11-16,11
3,5,1,EG(KKP)- und Monitoring-Planprobe,Frischobst einschließlich Rhabarber,Orange,Großhändler von Obst und Gemüse und -erzeugnissen,Australien und Ozeanien,Keine Angabe,Keine Angabe,2023-10-10,10
4,6,0,Monitoring-Planprobe,Fleisch warmblütiger Tiere auch tiefgefroren,Fleischteilstück Wildschwein auch tiefgefroren,Lebensmittelgeschäft und (eigenständige) -verkaufsabteilung (incl. Supermarkt),Deutschland,Unverarbeitet/roh,Verpackt unter Vakuum,2023-04-25,4


# Construction of the Preliminary Sample-Level Modelling Dataset

The analytical-record-level BVL dataset was transformed into a preliminary sample-level modelling dataset.

The original dataset contains **2,151,894 analytical records**, representing repeated analytical measurements performed on individual food samples.

For predictive modelling, the unit of analysis was changed to the individual food sample represented by "ProbenNrPseud" (Pseudonymised Sample Number).

## Final Structure

The preliminary modelling dataset contains:

- **8,582 food samples**
- **11 variables**
- **0 duplicate sample identifiers**
- **0 missing values after the defined feature transformations**

The preliminary target distribution is:

- Target 0 — no clearly adverse result: **8,511 samples (99.17%)**
- Target 1 — at least one clearly adverse result: **71 samples (0.83%)**

## Current Variables

The dataset currently contains:

- "ProbenNrPseud" (Pseudonymised Sample Number)
- "Target_Adverse" (Adverse Target)
- "PnMgT" (Sampling Programme Description)
- "MatrixGrT" (Matrix Group Description)
- "MatrixT" (Matrix Description)
- "BetriebsartT" (Business Type Description)
- "Country_Feature" (Country of Origin Feature)
- "Processing_Feature" (Processing Feature)
- "Packaging_Feature" (Packaging Feature)
- "Sampling_Date" (Sampling Date)
- "Sampling_Month" (Sampling Month)

## Modelling Interpretation

Each row now represents exactly one food sample rather than one analytical measurement.

This is important because the original analytical dataset contained many repeated laboratory measurements for the same sample.

Using a sample-level structure prevents samples with many analytical measurements from being disproportionately represented in the predictive model.

"ProbenNrPseud" (Pseudonymised Sample Number) is retained as an identifier for traceability but will **not be used as a predictive feature**.

Variables used directly to construct "Target_Adverse" (Adverse Target), including "Bewertung" (Assessment) and "BewertungT" (Assessment Description), are excluded from the predictor dataset to prevent target leakage.

## Class-Imbalance Consideration

The target remains severely imbalanced, with only **71 adverse samples among 8,582 food samples**.

Consequently, model evaluation will not rely on accuracy alone.

Metrics such as precision, recall, F1-score, confusion matrix results and precision-recall performance will be considered during modelling.

Class-weighting and appropriate resampling approaches will also be evaluated using the training data only.

In [61]:
# Save the preliminary sample-level modelling dataset

processed_path = "Data/processed/food_safety_sample_level.csv"

model_df.to_csv(
    processed_path,
    index=False
)

print("Saved successfully:")
print(processed_path)

print("\nSaved shape:")
print(model_df.shape)

Saved successfully:
Data/processed/food_safety_sample_level.csv

Saved shape:
(8582, 11)
